/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.NumberTheory.EffectiveBounds.HermiteCount

/-!
# Monotone forms of the effective Hermite--Minkowski count

`TauCeti.NumberField.ncard_setOf_finiteDimensional_abs_discr_le_le` gives an explicit
Hermite--Minkowski count in terms of Mathlib's exact constants
`NumberField.hermiteTheorem.rankOfDiscrBdd N` and
`TauCeti.NumberField.coeffBoundOfDiscrBdd N`. Later effective work often replaces those constants
by simpler upper bounds before doing arithmetic. This file records the monotone wrapper that permits
that replacement without unfolding the proof of the count.

This is a small API layer for the effective-bounds roadmap's Layer 2 summit: explicit upper bounds
on the number of number fields of bounded discriminant.

## Main results

* `TauCeti.NumberField.hermiteCountBound`: the polynomial-count expression attached to degree and
  coefficient bounds.
* `TauCeti.NumberField.hermiteCountBound_mono`: monotonicity in both bounds.
* `TauCeti.NumberField.ncard_setOf_finiteDimensional_abs_discr_le_le_of_bounds`: the effective
  Hermite--Minkowski count using any larger degree and coefficient bounds.
-/

public section

open Module NumberField NumberField.hermiteTheorem

namespace TauCeti.NumberField

variable (A : Type*) [Field A] [CharZero A]

/-- The elementary polynomial count appearing in effective Hermite--Minkowski: if every field is
generated by a root of an integer polynomial of degree at most `D` and coefficient height at most
`C`, then the number of possible generated fields is bounded by
`(2 * C + 1) ^ (D + 1) * D`. -/
def hermiteCountBound (D C : ℕ) : ℕ :=
  (2 * C + 1) ^ (D + 1) * D

@[simp]
theorem hermiteCountBound_def (D C : ℕ) :
    hermiteCountBound D C = (2 * C + 1) ^ (D + 1) * D :=
  by simp [hermiteCountBound]

@[simp]
theorem hermiteCountBound_zero_left (C : ℕ) : hermiteCountBound 0 C = 0 := by
  simp [hermiteCountBound]

@[simp]
theorem hermiteCountBound_zero_right (D : ℕ) : hermiteCountBound D 0 = D := by
  simp [hermiteCountBound]

/-- The Hermite-count expression is monotone in the degree bound and the coefficient-height
bound. -/
theorem hermiteCountBound_mono {D₁ D₂ C₁ C₂ : ℕ} (hD : D₁ ≤ D₂) (hC : C₁ ≤ C₂) :
    hermiteCountBound D₁ C₁ ≤ hermiteCountBound D₂ C₂ := by
  unfold hermiteCountBound
  gcongr
  omega

attribute [gcongr] hermiteCountBound_mono

/-- The effective Hermite--Minkowski count with the exact constants packaged as
`hermiteCountBound`. -/
theorem ncard_setOf_finiteDimensional_abs_discr_le_le_hermiteCountBound (N : ℕ) :
    {K : {F : IntermediateField ℚ A // FiniteDimensional ℚ F} |
        haveI : _root_.NumberField K := @NumberField.mk _ _ inferInstance K.prop
        |discr K| ≤ (N : ℤ)}.ncard ≤
      hermiteCountBound (rankOfDiscrBdd N) (coeffBoundOfDiscrBdd N) := by
  simpa [hermiteCountBound] using
    ncard_setOf_finiteDimensional_abs_discr_le_le (A := A) N

/-- **Monotone effective Hermite--Minkowski.** If `D` and `C` are any explicit bounds above
Mathlib's degree bound `rankOfDiscrBdd N` and the coefficient bound `coeffBoundOfDiscrBdd N`, then
the number of finite-dimensional subfields of an ambient extension `A / ℚ` with discriminant at
most `N` is bounded by `(2 * C + 1) ^ (D + 1) * D`.

This is the usable form for later explicit estimates, where `D` and `C` are often replaced by
simpler closed-form upper bounds. -/
theorem ncard_setOf_finiteDimensional_abs_discr_le_le_of_bounds (N D C : ℕ)
    (hD : rankOfDiscrBdd N ≤ D) (hC : coeffBoundOfDiscrBdd N ≤ C) :
    {K : {F : IntermediateField ℚ A // FiniteDimensional ℚ F} |
        haveI : _root_.NumberField K := @NumberField.mk _ _ inferInstance K.prop
        |discr K| ≤ (N : ℤ)}.ncard ≤
      hermiteCountBound D C :=
  (ncard_setOf_finiteDimensional_abs_discr_le_le_hermiteCountBound (A := A) N).trans
    (hermiteCountBound_mono hD hC)

end TauCeti.NumberField
