/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import TauCeti.NumberTheory.EffectiveBounds.Discriminant
import TauCeti.FieldTheory.Trace
import Mathlib.LinearAlgebra.FiniteDimensional.Lemmas

/-!
# The effective discriminant bound for a quadratic field, evaluated on a square-root basis

The effective discriminant bound `|d_K| ≤ |disc b|`
(`TauCeti.NumberField.abs_discr_le_of_basis_isIntegral`) is only useful once one can
*evaluate* `disc b` on a concrete basis. For a quadratic field generated by a square root,
the cheapest basis is `{1, x}` with `x² ∈ ℚ`, and the trace-form discriminant there is
`disc ℚ {1, x} = 4·x²` (`TauCeti.Algebra.discr_one_elem_eq_of_sq_algebraMap`, the
trace-form diagonalisation). Feeding an *integer* square root `x² = a ∈ ℤ` into the bound
turns these two pieces into a single closed-form estimate

`|d_K| ≤ 4·|a|`

for every quadratic field `K = ℚ(x)` with `x² = a ∈ ℤ`. This is precisely the tool the
roadmap's quadratic worked examples need: `ℚ(i)` (`a = -1`) gives `|d_K| ≤ 4`, and
`ℚ(√-5)` (`a = -5`) gives `|d_K| ≤ 20`.

The real content beyond the two cited lemmas is the basis construction: a square root `x`
outside `ℚ` makes `{1, x}` linearly independent, and in a quadratic field that family is a
`ℚ`-basis of algebraic integers, so the effective bound applies to it.

## Main results

* `TauCeti.NumberField.abs_discr_le_of_sq_intCast`: `|d_K| ≤ 4·|a|` (over `ℚ`) for a
  quadratic field `K` and `x : K` with `x² = a ∈ ℤ` and `x ∉ ℚ`.
* `TauCeti.NumberField.abs_discr_le_of_sq_intCast'`: the same bound stated entirely over
  `ℤ`, `|d_K| ≤ 4·|a|`.

## Provenance

The two consumed ingredients are migrated from
[kim-em/erdos-unit-distance](https://github.com/kim-em/erdos-unit-distance), the
formalization of L. Alpöge's disproof of the uniform-constant Erdős unit-distance
conjecture: the effective discriminant bound and the square-root trace-form
diagonalisation. The closed-form quadratic estimate assembled here is new.
-/

open Module

namespace TauCeti

namespace NumberField

/-- For a quadratic number field `K` and an element `x : K` whose square is an integer
`a` and which is not rational, the field discriminant satisfies `|d_K| ≤ 4·|a|`.

The square-root basis `{1, x}` consists of algebraic integers, so the effective bound
`abs_discr_le_of_basis_isIntegral` applies, and the trace-form diagonalisation evaluates
its discriminant as `disc ℚ {1, x} = 4·a`. -/
theorem abs_discr_le_of_sq_intCast {K : Type*} [Field K] [NumberField K]
    {x : K} {a : ℤ} (hfin : finrank ℚ K = 2)
    (hx2 : x ^ 2 = algebraMap ℤ K a) (hx : x ∉ (algebraMap ℚ K).range) :
    |(NumberField.discr K : ℚ)| ≤ 4 * |(a : ℚ)| := by
  classical
  -- The square root also satisfies `x² = (a : ℚ)` through the `ℚ`-algebra structure.
  have hcast : algebraMap ℤ K a = algebraMap ℚ K (a : ℚ) := by
    rw [IsScalarTower.algebraMap_apply ℤ ℚ K, eq_intCast (algebraMap ℤ ℚ) a]
  have hx2' : x ^ 2 = algebraMap ℚ K (a : ℚ) := hx2.trans hcast
  -- `x ≠ 0`, else `x = algebraMap ℚ K 0` would be rational.
  have hxne : x ≠ 0 := by
    rintro rfl
    exact hx ⟨0, by rw [map_zero]⟩
  -- `{1, x}` is linearly independent over `ℚ`: `x` is nonzero and not a `ℚ`-multiple of `1`.
  have hli : LinearIndependent ℚ ![1, x] := by
    rw [linearIndependent_fin2]
    refine ⟨by simpa using hxne, ?_⟩
    intro c hc
    simp only [Matrix.cons_val_one, Matrix.cons_val_zero] at hc
    rw [Algebra.smul_def] at hc
    refine hx ⟨c⁻¹, ?_⟩
    rw [map_inv₀]
    exact inv_eq_of_mul_eq_one_right hc
  -- A linearly independent family of `finrank` vectors is a basis.
  have hcard : Fintype.card (Fin 2) = finrank ℚ K := by
    rw [Fintype.card_fin]; exact hfin.symm
  set b := basisOfLinearIndependentOfCardEqFinrank' ![1, x] hli hcard with hb_def
  have hbcoe : ⇑b = ![1, x] := coe_basisOfLinearIndependentOfCardEqFinrank' _ _ _
  -- The basis consists of algebraic integers: `1` is integral, and `x` is a root of `X² - a`.
  have hxint : IsIntegral ℤ x := by
    refine ⟨Polynomial.X ^ 2 - Polynomial.C a,
      Polynomial.monic_X_pow_sub_C a (by norm_num), ?_⟩
    rw [Polynomial.eval₂_sub, Polynomial.eval₂_X_pow, Polynomial.eval₂_C, ← hx2, sub_self]
  have hb_int : ∀ i, IsIntegral ℤ (b i) := by
    intro i
    rw [show (b i) = ![1, x] i from by rw [hbcoe]]
    fin_cases i
    · simpa using (isIntegral_one : IsIntegral ℤ (1 : K))
    · simpa using hxint
  -- Combine the effective bound with the trace-form evaluation `disc ℚ {1, x} = 4·a`.
  have hmain := TauCeti.NumberField.abs_discr_le_of_basis_isIntegral b hb_int
  rw [hbcoe, TauCeti.Algebra.discr_one_elem_eq_of_sq_algebraMap hfin hx2' hx] at hmain
  rwa [abs_mul, show |(4 : ℚ)| = 4 by norm_num] at hmain

/-- The integer form of the quadratic discriminant bound: `|d_K| ≤ 4·|a|` over `ℤ`, for a
quadratic field `K` with `x² = a ∈ ℤ` and `x ∉ ℚ`. -/
theorem abs_discr_le_of_sq_intCast' {K : Type*} [Field K] [NumberField K]
    {x : K} {a : ℤ} (hfin : finrank ℚ K = 2)
    (hx2 : x ^ 2 = algebraMap ℤ K a) (hx : x ∉ (algebraMap ℚ K).range) :
    |NumberField.discr K| ≤ 4 * |a| := by
  exact_mod_cast abs_discr_le_of_sq_intCast hfin hx2 hx

end NumberField

end TauCeti
