/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.NumberTheory.EffectiveBounds.ClassNumberUnitSquares
public import TauCeti.NumberTheory.EffectiveBounds.QuadraticDiscriminant

/-!
# Class-number/unit-square product bounds for quadratic square-root fields

The Layer-1 EffectiveBounds estimates give

* the square-root discriminant bound `|d_K| ≤ 4 * |a|` for a quadratic number field generated by
  an algebraic integer `x` with `x ^ 2 = a ∈ ℤ`;
* the product bound
  `h_K * [O_K^× : (O_K^×)^2] ≤ |d_K| * 8^[K:ℚ]`.

This file composes them in the quadratic square-root case. The resulting closed form

`h_K * [O_K^× : (O_K^×)^2] ≤ 256 * |a|`

is the finite-factor package needed by later effective estimates when a small quadratic field is
presented by a square root, such as the roadmap's `ℚ(√-5)` worked example.

## Main results

* `TauCeti.NumberField.classNumber_mul_units_sq_index_le_natAbs_of_sq_intCast`: the product bound
  with the unit-square index.
* `TauCeti.NumberField.classNumber_mul_card_units_elementaryTwoQuotient_le_natAbs_of_sq_intCast`:
  the same bound for the elementary-2 quotient `O_K^×/(O_K^×)^2`.

No formal code is vendored. The proof only composes existing EffectiveBounds estimates, whose
source attribution is in `TauCeti/NumberTheory/EffectiveBounds/Discriminant.lean`,
`TauCeti/NumberTheory/EffectiveBounds/ClassNumber.lean`, and
`TauCeti/NumberTheory/EffectiveBounds/UnitSquares.lean`.
-/

public section

open scoped NumberField

namespace TauCeti.NumberField

open Module NumberField

private lemma intCast_four_mul_natAbs (a : ℤ) :
    ((4 * a.natAbs : ℕ) : ℤ) = 4 * |a| := by
  rw [Nat.cast_mul, Int.abs_eq_natAbs]
  norm_num

private lemma four_mul_natAbs_mul_eight_sq (a : ℤ) :
    4 * a.natAbs * 8 ^ 2 = 256 * a.natAbs := by
  omega

/-- **Quadratic square-root class-number/unit-square product bound.** If `K` is a quadratic
number field generated by an algebraic integer `x` with `x² = a ∈ ℤ` and `x ∉ ℚ`, then
`h_K * [O_K^× : (O_K^×)^2] ≤ 256 * |a|`. This is the specialization of the general product
bound using `|d_K| ≤ 4 * |a|` and `[K : ℚ] = 2`. -/
theorem classNumber_mul_units_sq_index_le_natAbs_of_sq_intCast
    {K : Type*} [Field K] [NumberField K] {x : K} {a : ℤ}
    (hfin : finrank ℚ K = 2) (hx2 : x ^ 2 = algebraMap ℤ K a)
    (hx : x ∉ (algebraMap ℚ K).range) :
    NumberField.classNumber K * (Subgroup.square (𝓞 K)ˣ).index ≤ 256 * a.natAbs := by
  have hD : |NumberField.discr K| ≤ (4 * a.natAbs : ℕ) := by
    rw [intCast_four_mul_natAbs]
    exact abs_discr_le_int_of_sq_intCast hfin hx2 hx
  have hprod :=
    classNumber_mul_units_sq_index_le_of_abs_discr_le_of_finrank_le K hD (le_of_eq hfin)
  rw [← four_mul_natAbs_mul_eight_sq]
  exact hprod

/-- A version of
`TauCeti.NumberField.classNumber_mul_units_sq_index_le_natAbs_of_sq_intCast` with a separate
natural-number bound for `|a|`. -/
theorem classNumber_mul_units_sq_index_le_of_sq_intCast_of_natAbs_le
    {K : Type*} [Field K] [NumberField K] {x : K} {a : ℤ} {A : ℕ}
    (hfin : finrank ℚ K = 2) (hx2 : x ^ 2 = algebraMap ℤ K a)
    (hx : x ∉ (algebraMap ℚ K).range) (hA : a.natAbs ≤ A) :
    NumberField.classNumber K * (Subgroup.square (𝓞 K)ˣ).index ≤ 256 * A :=
  (classNumber_mul_units_sq_index_le_natAbs_of_sq_intCast hfin hx2 hx).trans
    (Nat.mul_le_mul_left 256 hA)

/-- **Quadratic square-root elementary-2 quotient product bound.** If `K` is a quadratic number
field generated by an algebraic integer `x` with `x² = a ∈ ℤ` and `x ∉ ℚ`, then
`h_K * #(O_K^×/(O_K^×)^2) ≤ 256 * |a|`. This is the elementary-2 quotient form of
`TauCeti.NumberField.classNumber_mul_units_sq_index_le_natAbs_of_sq_intCast`. -/
theorem classNumber_mul_card_units_elementaryTwoQuotient_le_natAbs_of_sq_intCast
    {K : Type*} [Field K] [NumberField K] {x : K} {a : ℤ}
    (hfin : finrank ℚ K = 2) (hx2 : x ^ 2 = algebraMap ℤ K a)
    (hx : x ∉ (algebraMap ℚ K).range) :
    NumberField.classNumber K * Nat.card (TauCeti.ElementaryTwoQuotient (𝓞 K)ˣ) ≤
      256 * a.natAbs := by
  rw [TauCeti.card_elementaryTwoQuotient_eq_index_square]
  exact classNumber_mul_units_sq_index_le_natAbs_of_sq_intCast hfin hx2 hx

/-- A version of
`TauCeti.NumberField.classNumber_mul_card_units_elementaryTwoQuotient_le_natAbs_of_sq_intCast`
with a separate natural-number bound for `|a|`. -/
theorem classNumber_mul_card_units_elementaryTwoQuotient_le_of_sq_intCast_of_natAbs_le
    {K : Type*} [Field K] [NumberField K] {x : K} {a : ℤ} {A : ℕ}
    (hfin : finrank ℚ K = 2) (hx2 : x ^ 2 = algebraMap ℤ K a)
    (hx : x ∉ (algebraMap ℚ K).range) (hA : a.natAbs ≤ A) :
    NumberField.classNumber K * Nat.card (TauCeti.ElementaryTwoQuotient (𝓞 K)ˣ) ≤
      256 * A :=
  (classNumber_mul_card_units_elementaryTwoQuotient_le_natAbs_of_sq_intCast hfin hx2 hx).trans
    (Nat.mul_le_mul_left 256 hA)

end TauCeti.NumberField
