/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.NumberTheory.EffectiveBounds.ClassNumber
public import TauCeti.NumberTheory.EffectiveBounds.QuadraticDiscriminant

/-!
# The effective class-number bound for quadratic square-root fields

The Layer-1 effective-bounds roadmap supplies two independent estimates:

* `TauCeti.NumberField.abs_discr_le_of_sq_intCast`: if a quadratic number field `K` is
  generated by an algebraic integer `x` with `x² = a ∈ ℤ`, then `|d_K| ≤ 4·|a|`;
* `TauCeti.NumberField.classNumber_le_of_abs_discr_le_of_finrank_le`: if
  `|d_F| ≤ D` and `[F : ℚ] ≤ n`, then `h_F ≤ D·4^n`.

This file composes them in the quadratic case. It is the closed-form worked-example
corollary needed to turn a square-root model of a quadratic field directly into an explicit
class-number estimate. For instance, the roadmap's `ℚ(√-5)` example has `a = -5`, so this
specialized corollary gives `h_K ≤ 64·5`; the sharper unspecialized Layer-1 bound still gives
`h_K ≤ |d_K|·16` once the exact discriminant is known.

## Main results

* `TauCeti.NumberField.classNumber_le_of_sq_intCast`: the real-valued bound
  `h_K ≤ 64·|a|`.
* `TauCeti.NumberField.classNumber_le_natAbs_of_sq_intCast`: the same bound with a natural
  number right hand side.

No formal code is vendored. The proof only composes the existing EffectiveBounds
discriminant and class-number estimates, both of which already carry the required
attribution to `kim-em/erdos-unit-distance`.
-/

public section

namespace TauCeti.NumberField

open Module

-- Normalize the natural right-hand side of the integer discriminant estimate.
private lemma intCast_four_mul_natAbs (a : ℤ) :
    ((4 * a.natAbs : ℕ) : ℤ) = 4 * |a| := by
  rw [Nat.cast_mul, Int.abs_eq_natAbs]
  norm_num

-- Normalize the closed-form natural class-number bound after specializing the degree to `2`.
private lemma four_mul_natAbs_mul_four_sq (a : ℤ) :
    4 * a.natAbs * 4 ^ 2 = 64 * a.natAbs := by
  omega

/-- **Quadratic square-root class-number bound.** If `K` is a quadratic number field
generated by an algebraic integer `x` with `x² = a ∈ ℤ` and `x ∉ ℚ`, then
`h_K ≤ 64·|a|`. This is the specialization of the general effective class-number bound
using the square-root discriminant estimate `|d_K| ≤ 4·|a|` and `[K : ℚ] = 2`. -/
theorem classNumber_le_of_sq_intCast {K : Type*} [Field K] [NumberField K]
    {x : K} {a : ℤ} (hfin : finrank ℚ K = 2)
    (hx2 : x ^ 2 = algebraMap ℤ K a) (hx : x ∉ (algebraMap ℚ K).range) :
    (NumberField.classNumber K : ℝ) ≤ 64 * |(a : ℝ)| := by
  have hD : |(NumberField.discr K : ℝ)| ≤ 4 * |(a : ℝ)| := by
    exact_mod_cast abs_discr_le_int_of_sq_intCast hfin hx2 hx
  have hclass :
      (NumberField.classNumber K : ℝ) ≤ (4 * |(a : ℝ)|) * 4 ^ 2 :=
    classNumber_le_of_abs_discr_le_of_finrank_le K hD (le_of_eq hfin)
  nlinarith [hclass]

/-- Natural-number form of `TauCeti.NumberField.classNumber_le_of_sq_intCast`:
for a quadratic number field generated by an algebraic integer square root `x² = a`,
`h_K ≤ 64 * a.natAbs`. -/
theorem classNumber_le_natAbs_of_sq_intCast {K : Type*} [Field K] [NumberField K]
    {x : K} {a : ℤ} (hfin : finrank ℚ K = 2)
    (hx2 : x ^ 2 = algebraMap ℤ K a) (hx : x ∉ (algebraMap ℚ K).range) :
    NumberField.classNumber K ≤ 64 * a.natAbs := by
  have hD : |NumberField.discr K| ≤ (4 * a.natAbs : ℕ) := by
    rw [intCast_four_mul_natAbs]
    exact abs_discr_le_int_of_sq_intCast hfin hx2 hx
  have hclass :=
    classNumber_le_nat_of_abs_discr_le_of_finrank_le K hD (le_of_eq hfin)
  rw [← four_mul_natAbs_mul_four_sq]
  exact hclass

/-- A version of `TauCeti.NumberField.classNumber_le_of_sq_intCast` with a separate
natural-number bound for `|a|`. -/
theorem classNumber_le_of_sq_intCast_of_natAbs_le {K : Type*} [Field K] [NumberField K]
    {x : K} {a : ℤ} {A : ℕ} (hfin : finrank ℚ K = 2)
    (hx2 : x ^ 2 = algebraMap ℤ K a) (hx : x ∉ (algebraMap ℚ K).range)
    (hA : a.natAbs ≤ A) :
    NumberField.classNumber K ≤ 64 * A :=
  (classNumber_le_natAbs_of_sq_intCast hfin hx2 hx).trans (Nat.mul_le_mul_left 64 hA)

end TauCeti.NumberField
