/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib.NumberTheory.NumberField.Units.DirichletTheorem
import TauCeti.Algebra.Group.PowMonoidHom

/-!
# The index of squares in the unit group of a number field

For a number field `F`, the subgroup of squares of the unit group has index at most `2^[F:ℚ]`:

`[O_F^× : (O_F^×)²] ≤ 2^[F:ℚ]`.

By Dirichlet's unit theorem `O_F^×` is generated by the fundamental system (of size `rank`)
together with a generator of the finite cyclic torsion subgroup, so it is generated by
`rank + 1 ≤ [F:ℚ]` elements; `TauCeti.index_square_le_of_closure_eq_top` then controls the
index of the squares.

## Main results

* `TauCeti.NumberField.units_sq_index_le`: `[O_F^× : (O_F^×)²] ≤ 2^[F:ℚ]`.

## Provenance

Migrated from
[kim-em/erdos-unit-distance](https://github.com/kim-em/erdos-unit-distance), the
formalization of L. Alpöge's disproof of the uniform-constant Erdős unit-distance
conjecture, where this bound fed an explicit class-number estimate.
-/

open NumberField NumberField.Units

namespace TauCeti.NumberField

/-- **Squares have small index in the unit group.** `[O_F^× : (O_F^×)²] ≤ 2^[F:ℚ]`, stated
using Mathlib's `Subgroup.square` for the subgroup of squares. By Dirichlet's unit theorem
`O_F^×` is generated by the `rank`-element fundamental system together with a torsion
generator, so `TauCeti.index_square_le_of_closure_eq_top` bounds the index by `2^(rank+1)`,
and `rank + 1 ≤ [F:ℚ]`. -/
theorem units_sq_index_le (F : Type*) [Field F] [NumberField F] :
    (Subgroup.square (𝓞 F)ˣ).index ≤ 2 ^ Module.finrank ℚ F := by
  classical
  -- A finite generating set: the fundamental system together with a torsion generator.
  obtain ⟨ζ, hζ⟩ := IsCyclic.exists_generator (α := torsion F)
  set S : Finset (𝓞 F)ˣ :=
    insert (ζ : (𝓞 F)ˣ) (Finset.image (fundSystem F) Finset.univ) with hSdef
  have hζS : (ζ : (𝓞 F)ˣ) ∈ Subgroup.closure (S : Set (𝓞 F)ˣ) :=
    Subgroup.subset_closure (Finset.mem_coe.mpr (Finset.mem_insert_self _ _))
  have hgen : Subgroup.closure (S : Set (𝓞 F)ˣ) = ⊤ := by
    refine top_le_iff.mp ?_
    rw [← closure_fundSystem_sup_torsion_eq_top F, sup_le_iff]
    refine ⟨Subgroup.closure_mono ?_, ?_⟩
    · rw [hSdef]
      simp only [Finset.coe_insert, Finset.coe_image, Finset.coe_univ, Set.image_univ]
      exact Set.subset_insert _ _
    · intro t ht
      obtain ⟨n, hn⟩ := Subgroup.mem_zpowers_iff.mp (hζ ⟨t, ht⟩)
      have ht' : (ζ : (𝓞 F)ˣ) ^ n = t := by
        simpa [SubgroupClass.coe_zpow] using congrArg Subtype.val hn
      rw [← ht']
      exact zpow_mem hζS n
  -- The index bound, and the size of the generating set.
  refine (TauCeti.index_square_le_of_closure_eq_top hgen).trans
    (Nat.pow_le_pow_right (by norm_num) ?_)
  calc S.card ≤ (Finset.image (fundSystem F) Finset.univ).card + 1 := Finset.card_insert_le _ _
    _ ≤ rank F + 1 := by
        gcongr
        exact Finset.card_image_le.trans_eq (by rw [Finset.card_univ, Fintype.card_fin])
    _ ≤ Module.finrank ℚ F := by
        have h1 := InfinitePlace.card_eq_nrRealPlaces_add_nrComplexPlaces F
        have h2 := InfinitePlace.card_add_two_mul_card_eq_rank F
        have h3 : 0 < Fintype.card (InfinitePlace F) :=
          Fintype.card_pos_iff.mpr ⟨Classical.arbitrary _⟩
        simp only [rank]
        omega

end TauCeti.NumberField
