/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib.NumberTheory.NumberField.Units.DirichletTheorem

/-!
# The index of squares in the unit group of a number field

For a number field `F`, the squaring map on the unit group has index at most `2^[F:ℚ]`:

`[O_F^× : (O_F^×)²] ≤ 2^[F:ℚ]`.

By Dirichlet's unit theorem `O_F^×` is generated by the fundamental system (of size `rank`)
together with a generator of the finite cyclic torsion subgroup, so it is generated by
`rank + 1 ≤ [F:ℚ]` elements; an abstract bound then controls the index of squares in any
finitely generated commutative group.

## Main results

* `TauCeti.NumberField.index_powMonoidHom_two_le_of_closure`: in a commutative group generated
  by a finite set `S`, the subgroup of squares has index at most `2 ^ S.card`.
* `TauCeti.NumberField.units_sq_index_le`: `[O_F^× : (O_F^×)²] ≤ 2^[F:ℚ]`.

## Provenance

Migrated from
[kim-em/erdos-unit-distance](https://github.com/kim-em/erdos-unit-distance), the
formalization of L. Alpöge's disproof of the uniform-constant Erdős unit-distance
conjecture, where this bound fed an explicit class-number estimate.
-/

open NumberField NumberField.Units

namespace TauCeti.NumberField

/-- For an element of order dividing two, an integer power depends only on the exponent
modulo two. -/
private theorem zpow_eq_zpow_emod_two {G : Type*} [Group G] {x : G} (hx : x ^ 2 = 1) (z : ℤ) :
    x ^ z = x ^ (z % 2) := by
  have hx2 : x ^ (2 : ℤ) = 1 := by exact_mod_cast hx
  have heven : x ^ (2 * (z / 2)) = 1 := by rw [zpow_mul, hx2, one_zpow]
  have hz : x ^ z = x ^ (2 * (z / 2)) * x ^ (z % 2) := by
    rw [← zpow_add]; congr 1; omega
  rw [hz, heven, one_mul]

/-- In a commutative group generated by a finite set `S`, the subgroup of squares has index at
most `2 ^ S.card`. The quotient by the squares is an elementary abelian `2`-group spanned by
the image of `S`, so it has at most `2 ^ S.card` elements. -/
theorem index_powMonoidHom_two_le_of_closure {G : Type*} [CommGroup G] {S : Finset G}
    (hS : Subgroup.closure (S : Set G) = ⊤) :
    (powMonoidHom 2 : G →* G).range.index ≤ 2 ^ S.card := by
  classical
  set H := (powMonoidHom 2 : G →* G).range with hH
  set mk : G →* G ⧸ H := QuotientGroup.mk' H with hmk
  -- Every element of `G` is an integer-power product over `S`.
  have hpow : ∀ g : G, ∃ z : S → ℤ, g = ∏ s : S, (s : G) ^ z s := by
    intro g
    have hg : g ∈ Subgroup.closure (S : Set G) := hS ▸ Subgroup.mem_top g
    induction hg using Subgroup.closure_induction with
    | mem x hx =>
        refine ⟨fun s => if s = ⟨x, hx⟩ then 1 else 0, ?_⟩
        rw [Finset.prod_eq_single (⟨x, hx⟩ : S)] <;> simp +contextual
    | one => exact ⟨0, by simp⟩
    | mul x y _ _ hx hy =>
        obtain ⟨zx, rfl⟩ := hx
        obtain ⟨zy, rfl⟩ := hy
        exact ⟨zx + zy, by simp [zpow_add, Finset.prod_mul_distrib]⟩
    | inv x _ hx =>
        obtain ⟨zx, rfl⟩ := hx
        exact ⟨-zx, by simp [zpow_neg, Finset.prod_inv_distrib]⟩
  -- In the quotient each generator has order dividing two.
  have hsq : ∀ s : S, mk (s : G) ^ 2 = 1 := fun s => by
    rw [← map_pow, hmk, QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff]
    exact ⟨(s : G), rfl⟩
  -- Every quotient element is a `{0,1}`-exponent product of the generators.
  have hsurj : Function.Surjective
      (fun f : S → Fin 2 => ∏ s : S, mk (s : G) ^ (f s : ℕ)) := by
    intro q
    obtain ⟨g, rfl⟩ := QuotientGroup.mk'_surjective H q
    obtain ⟨z, rfl⟩ := hpow g
    refine ⟨fun s => ⟨(z s % 2).toNat, by omega⟩, ?_⟩
    rw [hmk, map_prod]
    refine Finset.prod_congr rfl fun s _ => ?_
    rw [map_zpow, ← hmk]
    conv_rhs => rw [zpow_eq_zpow_emod_two (hsq s)]
    rw [← zpow_natCast (mk (s : G)) (z s % 2).toNat,
      Int.toNat_of_nonneg (Int.emod_nonneg _ (by norm_num))]
  calc (powMonoidHom 2 : G →* G).range.index
      = Nat.card (G ⧸ H) := rfl
    _ ≤ Nat.card (S → Fin 2) := Nat.card_le_card_of_surjective _ hsurj
    _ = 2 ^ S.card := by
        rw [Nat.card_eq_fintype_card, Fintype.card_fun, Fintype.card_fin, Fintype.card_coe]

/-- **Squares have small index in the unit group.** `[O_F^× : (O_F^×)²] ≤ 2^[F:ℚ]`. By
Dirichlet's unit theorem `O_F^×` is generated by the `rank`-element fundamental system together
with a torsion generator, so by `index_powMonoidHom_two_le_of_closure` the index is at most
`2^(rank+1)`, and `rank + 1 ≤ [F:ℚ]`. -/
theorem units_sq_index_le (F : Type*) [Field F] [NumberField F] :
    (powMonoidHom 2 : (𝓞 F)ˣ →* (𝓞 F)ˣ).range.index ≤ 2 ^ Module.finrank ℚ F := by
  classical
  -- A finite generating set: the fundamental system together with a torsion generator.
  obtain ⟨ζ, hζ⟩ := IsCyclic.exists_generator (α := torsion F)
  set S : Finset (𝓞 F)ˣ :=
    insert (ζ : (𝓞 F)ˣ) (Finset.image (fundSystem F) Finset.univ) with hSdef
  have hζS : (ζ : (𝓞 F)ˣ) ∈ Subgroup.closure (S : Set (𝓞 F)ˣ) :=
    Subgroup.subset_closure (Finset.mem_coe.mpr (Finset.mem_insert_self _ _))
  have hgen : Subgroup.closure (S : Set (𝓞 F)ˣ) = ⊤ := by
    refine top_le_iff.mp ?_
    rw [← closure_fundSystem_sup_torsion_eq_top F, sup_le_iff]
    refine ⟨Subgroup.closure_mono ?_, ?_⟩
    · rw [hSdef]
      simp only [Finset.coe_insert, Finset.coe_image, Finset.coe_univ, Set.image_univ]
      exact Set.subset_insert _ _
    · intro t ht
      obtain ⟨n, hn⟩ := Subgroup.mem_zpowers_iff.mp (hζ ⟨t, ht⟩)
      have ht' : (ζ : (𝓞 F)ˣ) ^ n = t := by
        simpa [SubgroupClass.coe_zpow] using congrArg Subtype.val hn
      rw [← ht']
      exact zpow_mem hζS n
  -- The index bound, and the size of the generating set.
  refine (index_powMonoidHom_two_le_of_closure hgen).trans
    (Nat.pow_le_pow_right (by norm_num) ?_)
  calc S.card ≤ (Finset.image (fundSystem F) Finset.univ).card + 1 := Finset.card_insert_le _ _
    _ ≤ rank F + 1 := by
        gcongr
        exact Finset.card_image_le.trans_eq (by rw [Finset.card_univ, Fintype.card_fin])
    _ ≤ Module.finrank ℚ F := by
        have h1 := InfinitePlace.card_eq_nrRealPlaces_add_nrComplexPlaces F
        have h2 := InfinitePlace.card_add_two_mul_card_eq_rank F
        have h3 : 0 < Fintype.card (InfinitePlace F) :=
          Fintype.card_pos_iff.mpr ⟨Classical.arbitrary _⟩
        simp only [rank]
        omega

end TauCeti.NumberField
