/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib.NumberTheory.NumberField.Units.DirichletTheorem
import TauCeti.Algebra.Group.PowMonoidHom

/-!
# The index of powers in the unit group of a number field

For a number field `F`, the `n`th-power map on the unit group has index at most `n^[F:ℚ]`:

`[O_F^× : (O_F^×)^n] ≤ n^[F:ℚ]` for positive `n`.

In particular, the squaring map on the unit group has index at most `2^[F:ℚ]`:

`[O_F^× : (O_F^×)²] ≤ 2^[F:ℚ]`.

By Dirichlet's unit theorem `O_F^×` is generated by the fundamental system (of size `rank`)
together with a generator of the finite cyclic torsion subgroup, so it is generated by
`rank + 1 ≤ [F:ℚ]` elements; an abstract bound then controls the index of powers in any
finitely generated commutative group.

## Main results

* `TauCeti.index_range_powMonoidHom_le_of_closure_eq_top`: in a commutative group generated by a
  finite set `S`, the range of the `n`th-power map has index at most `n ^ S.card` for positive
  `n`.
* `TauCeti.NumberField.units_pow_index_le`: `[O_F^× : (O_F^×)^n] ≤ n^[F:ℚ]` for positive `n`.
* `TauCeti.NumberField.units_sq_index_le`: `[O_F^× : (O_F^×)²] ≤ 2^[F:ℚ]`.

## Provenance

Migrated from
[kim-em/erdos-unit-distance](https://github.com/kim-em/erdos-unit-distance), the
formalization of L. Alpöge's disproof of the uniform-constant Erdős unit-distance
conjecture, where this bound fed an explicit class-number estimate.
-/

open NumberField NumberField.Units

namespace TauCeti.NumberField

/-- **Positive powers have small index in the unit group.**
`[O_F^× : (O_F^×)^n] ≤ n^[F:ℚ]` for positive `n`. By Dirichlet's unit theorem `O_F^×` is
generated by the `rank`-element fundamental system together with a torsion generator, so by
`TauCeti.index_range_powMonoidHom_le_of_closure_eq_top` the index is at most `n^(rank+1)`, and
`rank + 1 ≤ [F:ℚ]`. -/
theorem units_pow_index_le (F : Type*) [Field F] [NumberField F] {n : ℕ} (hn : 0 < n) :
    (powMonoidHom n : (𝓞 F)ˣ →* (𝓞 F)ˣ).range.index ≤ n ^ Module.finrank ℚ F := by
  classical
  -- A finite generating set: the fundamental system together with a torsion generator.
  obtain ⟨ζ, hζ⟩ := IsCyclic.exists_generator (α := torsion F)
  set S : Finset (𝓞 F)ˣ :=
    insert (ζ : (𝓞 F)ˣ) (Finset.image (fundSystem F) Finset.univ) with hSdef
  have hζS : (ζ : (𝓞 F)ˣ) ∈ Subgroup.closure (S : Set (𝓞 F)ˣ) :=
    Subgroup.subset_closure (Finset.mem_coe.mpr (Finset.mem_insert_self _ _))
  have hgen : Subgroup.closure (S : Set (𝓞 F)ˣ) = ⊤ := by
    refine top_le_iff.mp ?_
    rw [← closure_fundSystem_sup_torsion_eq_top F, sup_le_iff]
    refine ⟨Subgroup.closure_mono ?_, ?_⟩
    · rw [hSdef]
      simp only [Finset.coe_insert, Finset.coe_image, Finset.coe_univ, Set.image_univ]
      exact Set.subset_insert _ _
    · intro t ht
      obtain ⟨n, hn⟩ := Subgroup.mem_zpowers_iff.mp (hζ ⟨t, ht⟩)
      have ht' : (ζ : (𝓞 F)ˣ) ^ n = t := by
        simpa [SubgroupClass.coe_zpow] using congrArg Subtype.val hn
      rw [← ht']
      exact zpow_mem hζS n
  -- The index bound, and the size of the generating set.
  refine (TauCeti.index_range_powMonoidHom_le_of_closure_eq_top hn hgen).trans
    (Nat.pow_le_pow_right hn ?_)
  calc S.card ≤ (Finset.image (fundSystem F) Finset.univ).card + 1 := Finset.card_insert_le _ _
    _ ≤ rank F + 1 := by
        gcongr
        exact Finset.card_image_le.trans_eq (by rw [Finset.card_univ, Fintype.card_fin])
    _ ≤ Module.finrank ℚ F := by
        have h1 := InfinitePlace.card_eq_nrRealPlaces_add_nrComplexPlaces F
        have h2 := InfinitePlace.card_add_two_mul_card_eq_rank F
        have h3 : 0 < Fintype.card (InfinitePlace F) :=
          Fintype.card_pos_iff.mpr ⟨Classical.arbitrary _⟩
        simp only [rank]
        omega

/-- **Squares have small index in the unit group.** `[O_F^× : (O_F^×)²] ≤ 2^[F:ℚ]`. -/
theorem units_sq_index_le (F : Type*) [Field F] [NumberField F] :
    (powMonoidHom 2 : (𝓞 F)ˣ →* (𝓞 F)ˣ).range.index ≤ 2 ^ Module.finrank ℚ F :=
  units_pow_index_le F (by norm_num)

end TauCeti.NumberField
