module

public import Mathlib.Probability.Process.Filtration
public import Mathlib.Order.LiminfLimsup
import Mathlib.Data.Stream.Init

/-!
# Tail σ-algebras of a process, and cons/tail of sequence-valued random variables

This file provides the process-relative tail σ-algebra API requested in the Exchangeability
roadmap, Layer 2.  For a process `X : (k : ℕ) → Ω → β k`, `tailFamily X n` is the
σ-algebra generated by the coordinates `X k` with `n ≤ k`, and `tailProcess X` is the Mathlib
tail σ-algebra `limsup ... atTop` of the coordinate σ-algebras.  The same future σ-algebras are
also bundled as a filtration indexed by `ℕᵒᵈ`, so later reverse-martingale statements can consume
Mathlib's `Filtration` interface.

It also provides the pointwise `Stream'.cons`/`Stream'.tail` operations `processCons`/`processTail`
on sequence-valued random variables `t : Ω → ℕ → α`, with their measurability and `comap`
σ-algebra-contraction lemmas — kept here because their contraction lemmas are exactly the tail
σ-algebra facts the Kallenberg conditional-independence step of the de Finetti factorisation needs.
-/

public section

noncomputable section

open Filter MeasureTheory

namespace TauCeti

namespace Probability

variable {Ω : Type*} {β : ℕ → Type*} [∀ k, MeasurableSpace (β k)]

/-- The σ-algebra generated by the future coordinates `X k` with `n ≤ k`. -/
@[expose, implicit_reducible]
def tailFamily (X : (k : ℕ) → Ω → β k) (n : ℕ) : MeasurableSpace Ω :=
  ⨆ k : {k : ℕ // n ≤ k}, MeasurableSpace.comap (X k.1) inferInstance

/-- The tail σ-algebra of a process, expressed as Mathlib's `limsup` tail σ-algebra. -/
@[expose, implicit_reducible]
def tailProcess (X : (k : ℕ) → Ω → β k) : MeasurableSpace Ω :=
  limsup (fun k => MeasurableSpace.comap (X k) inferInstance) atTop

/-- Normal form for the future σ-algebra generated by coordinates from `n` onward. -/
@[simp]
theorem tailFamily_eq_iSup_comap (X : (k : ℕ) → Ω → β k) (n : ℕ) :
    tailFamily X n =
      ⨆ k : {k : ℕ // n ≤ k}, MeasurableSpace.comap (X k.1) inferInstance :=
  rfl

/-- The process-relative tail σ-algebra is Mathlib's `limsup` tail σ-algebra. -/
theorem tailProcess_eq_limsup (X : (k : ℕ) → Ω → β k) :
    tailProcess X = limsup (fun k => MeasurableSpace.comap (X k) inferInstance) atTop :=
  rfl

/-- Normal form for the process-relative tail σ-algebra. -/
@[simp]
theorem tailProcess_eq_iInf_tailFamily (X : (k : ℕ) → Ω → β k) :
    tailProcess X = ⨅ n : ℕ, tailFamily X n := by
  rw [tailProcess_eq_limsup, limsup_eq_iInf_iSup_of_nat]
  exact iInf_congr fun n => (iSup_subtype
    (f := fun k : {k : ℕ // n ≤ k} => MeasurableSpace.comap (X k.1) inferInstance)).symm

/-- A future coordinate is measurable with respect to the corresponding future σ-algebra. -/
theorem measurable_tailFamily_of_le {X : (k : ℕ) → Ω → β k} {n k : ℕ}
    (hnk : n ≤ k) :
    Measurable[tailFamily X n] (X k) := by
  rw [measurable_iff_comap_le]
  exact le_iSup (fun k : {k : ℕ // n ≤ k} =>
    MeasurableSpace.comap (X k.1) inferInstance) ⟨k, hnk⟩

/-- Universal property of the future σ-algebra generated by coordinates from `n` onward. -/
theorem tailFamily_le_iff {X : (k : ℕ) → Ω → β k} {n : ℕ} {m : MeasurableSpace Ω} :
    tailFamily X n ≤ m ↔ ∀ k, n ≤ k → Measurable[m] (X k) := by
  constructor
  · intro h k hnk
    exact (measurable_tailFamily_of_le hnk).mono h le_rfl
  · intro h
    rw [tailFamily_eq_iSup_comap]
    exact iSup_le fun k => (h k.1 k.2).comap_le

/-- The future σ-algebras of a process form a decreasing family. -/
theorem tailFamily_antitone (X : (k : ℕ) → Ω → β k) :
    Antitone (tailFamily X) := by
  intro n m hnm
  rw [tailFamily_eq_iSup_comap, tailFamily_eq_iSup_comap]
  refine iSup_le ?_
  intro k
  exact le_iSup (fun k : {k : ℕ // n ≤ k} =>
    MeasurableSpace.comap (X k.1) inferInstance) ⟨k.1, hnm.trans k.2⟩

/-- The tail σ-algebra is contained in every future σ-algebra. -/
theorem tailProcess_le_tailFamily (X : (k : ℕ) → Ω → β k) (n : ℕ) :
    tailProcess X ≤ tailFamily X n := by
  rw [tailProcess_eq_iInf_tailFamily]
  exact iInf_le _ n

variable [MeasurableSpace Ω]

/-- If all coordinates are ambient-measurable, then each future σ-algebra is a sub-σ-algebra of
the ambient one. -/
theorem tailFamily_le_ambient {X : (k : ℕ) → Ω → β k} (n : ℕ)
    (hX : ∀ k, n ≤ k → Measurable (X k)) :
    tailFamily X n ≤ (inferInstance : MeasurableSpace Ω) :=
  tailFamily_le_iff.2 hX

/-- If the coordinates from some cutoff `n` onward are ambient-measurable, then the tail σ-algebra
is a sub-σ-algebra of the ambient one.  The tail does not see the finitely many initial
coordinates, so only eventual measurability is required. -/
theorem tailProcess_le_ambient {X : (k : ℕ) → Ω → β k} (n : ℕ)
    (hX : ∀ k, n ≤ k → Measurable (X k)) :
    tailProcess X ≤ (inferInstance : MeasurableSpace Ω) :=
  (tailProcess_le_tailFamily X n).trans (tailFamily_le_ambient n hX)

/-- The future σ-algebras bundled as an increasing filtration over the reversed order `ℕᵒᵈ`.
This is the filtration consumed by reverse-martingale arguments. -/
@[expose]
def futureFiltration (X : (k : ℕ) → Ω → β k) (hX : ∀ k, Measurable (X k)) :
    Filtration ℕᵒᵈ (inferInstance : MeasurableSpace Ω) where
  seq n := tailFamily X (OrderDual.ofDual n)
  mono' := by
    intro n m hnm
    exact tailFamily_antitone X hnm
  le' n := tailFamily_le_ambient (OrderDual.ofDual n) fun k _ => hX k

/-- Evaluating the reversed future filtration at `n : ℕᵒᵈ` gives the future σ-algebra
generated by coordinates from `OrderDual.ofDual n` onward. -/
@[simp]
theorem futureFiltration_apply (X : (k : ℕ) → Ω → β k) (hX : ∀ k, Measurable (X k))
    (n : ℕᵒᵈ) :
    futureFiltration X hX n = tailFamily X (OrderDual.ofDual n) :=
  rfl

/-- The process tail is the infimum of the reversed future filtration. -/
theorem tailProcess_eq_iInf_futureFiltration (X : (k : ℕ) → Ω → β k)
    (hX : ∀ k, Measurable (X k)) :
    tailProcess X = ⨅ n : ℕᵒᵈ, futureFiltration X hX n := by
  rw [tailProcess_eq_iInf_tailFamily]
  simpa using (OrderDual.toDual.surjective.iInf_comp
    (fun n : ℕᵒᵈ => futureFiltration X hX n))

/-- Every coordinate from the future is measurable with respect to the reversed future
filtration at that cutoff. -/
theorem measurable_futureFiltration_of_le {X : (k : ℕ) → Ω → β k}
    (hX : ∀ k, Measurable (X k)) {n k : ℕ} (hnk : n ≤ k) :
    Measurable[futureFiltration X hX (OrderDual.toDual n)] (X k) := by
  rw [futureFiltration_apply]
  exact measurable_tailFamily_of_le hnk

variable {α : Type*} [MeasurableSpace α]

/-- The path-space tail σ-algebra, i.e. the tail of the coordinate process on `ℕ → α`. -/
abbrev pathTail (α : Type*) [MeasurableSpace α] : MeasurableSpace (ℕ → α) :=
  tailProcess (fun k (x : ℕ → α) => x k)

/-- Normal form for the path-space tail σ-algebra. -/
@[simp]
theorem pathTail_eq_tailProcess :
    pathTail α = tailProcess (fun k (x : ℕ → α) => x k) :=
  rfl

/-- The path-space tail σ-algebra is contained in every future path σ-algebra from time `n`
onward. -/
theorem pathTail_le_tailFamily (n : ℕ) :
    pathTail α ≤ tailFamily (fun k (x : ℕ → α) => x k) n :=
  tailProcess_le_tailFamily _ n

/-! ## Cons and tail of sequence-valued random variables

`processCons` / `processTail` prepend / drop the leading coordinate of a sequence-valued random
variable `t : Ω → ℕ → α`.  The `comap` contraction lemmas (`comap_processTail_le`,
`comap_le_comap_processCons`) record that the tail generates a coarser σ-algebra and that consing
refines it; these feed the Kallenberg conditional-independence step of the de Finetti block-product
factorisation.  The definitions are not `@[expose]`; their characteristic API is the `@[simp]`
`_apply` / interaction lemmas below.

Adapted from `cameronfreer/exchangeability` (`DeFinetti/ViaMartingale/ShiftOperations.lean`, pin
`e0532e59ceff23edab44dda9ab0655debbc9cc22`). -/

/-- Cons a head random variable onto a sequence-valued one (a pointwise `Stream'.cons`):
`processCons x t = [x, t 0, t 1, …]`. -/
def processCons (x : Ω → α) (t : Ω → ℕ → α) : Ω → ℕ → α :=
  fun ω => Stream'.cons (x ω) (t ω)

omit [MeasurableSpace Ω] [MeasurableSpace α] in
/-- Leading coordinate of a cons: `processCons x t ω 0 = x ω`. -/
@[simp]
theorem processCons_zero (x : Ω → α) (t : Ω → ℕ → α) (ω : Ω) : processCons x t ω 0 = x ω := by
  simp only [processCons]
  exact Stream'.get_zero_cons (x ω) (t ω)

omit [MeasurableSpace Ω] [MeasurableSpace α] in
/-- Later coordinates of a cons: `processCons x t ω (n + 1) = t ω n`. -/
@[simp]
theorem processCons_succ (x : Ω → α) (t : Ω → ℕ → α) (ω : Ω) (n : ℕ) :
    processCons x t ω (n + 1) = t ω n := by
  simp only [processCons]
  exact Stream'.get_succ_cons n (t ω) (x ω)

/-- Drop the leading coordinate of a sequence-valued random variable (a pointwise `Stream'.tail`):
`processTail t ω n = t ω (n+1)`. -/
def processTail (t : Ω → ℕ → α) : Ω → ℕ → α :=
  fun ω => Stream'.tail (t ω)

omit [MeasurableSpace Ω] [MeasurableSpace α] in
/-- Coordinate equation for `processTail`: its `n`th coordinate is `t (n + 1)`. -/
@[simp]
theorem processTail_apply (t : Ω → ℕ → α) (ω : Ω) (n : ℕ) : processTail t ω n = t ω (n + 1) := by
  simp only [processTail, Stream'.tail, Stream'.get]

omit [MeasurableSpace Ω] [MeasurableSpace α] in
/-- The tail of a cons recovers the original sequence. -/
@[simp]
theorem processTail_processCons (x : Ω → α) (t : Ω → ℕ → α) :
    processTail (processCons x t) = t := by
  funext ω
  simp only [processTail, processCons]
  exact Stream'.tail_cons (x ω) (t ω)

omit [MeasurableSpace Ω] [MeasurableSpace α] in
/-- Reconstruct a sequence from its head and tail (the reverse of `processTail_processCons`). -/
@[simp]
theorem processCons_processTail (t : Ω → ℕ → α) :
    processCons (fun ω => t ω 0) (processTail t) = t := by
  funext ω n
  cases n with
  | zero => simp only [processCons_zero]
  | succ n => simp only [processCons_succ, processTail_apply]

/-- Consing a measurable head onto a process is measurable when its coordinates `t (· ·)` are. -/
@[fun_prop]
theorem measurable_processCons {x : Ω → α} {t : Ω → ℕ → α} (hx : Measurable x)
    (ht : ∀ n, Measurable fun ω => t ω n) : Measurable (processCons x t) := by
  refine measurable_pi_lambda _ fun n => ?_
  cases n with
  | zero => simpa only [processCons_zero] using hx
  | succ n => simpa only [processCons_succ] using ht n

/-- The tail of a process is measurable when its tail coordinates `t (· + 1)` are. -/
@[fun_prop]
theorem measurable_processTail {t : Ω → ℕ → α} (ht : ∀ n, Measurable fun ω => t ω (n + 1)) :
    Measurable (processTail t) := by
  refine measurable_pi_lambda _ fun n => ?_
  simpa only [processTail_apply] using ht n

omit [MeasurableSpace Ω] in
/-- The tail of a sequence-valued random variable generates a coarser σ-algebra than the variable
itself. -/
theorem comap_processTail_le {t : Ω → ℕ → α} :
    MeasurableSpace.comap (processTail t) inferInstance
      ≤ MeasurableSpace.comap t inferInstance := by
  have hcomp : processTail t = (fun s : ℕ → α => fun n => s (n + 1)) ∘ t := by
    funext ω n; simp only [processTail, Stream'.tail, Stream'.get, Function.comp_apply]
  rw [hcomp, ← MeasurableSpace.comap_comp]
  have hshift : Measurable fun s : ℕ → α => fun n => s (n + 1) := by fun_prop
  exact MeasurableSpace.comap_mono hshift.comap_le

omit [MeasurableSpace Ω] in
/-- Consing a head onto a sequence-valued random variable refines its σ-algebra: `σ(t) ≤
σ(processCons x t)`. -/
theorem comap_le_comap_processCons (x : Ω → α) (t : Ω → ℕ → α) :
    MeasurableSpace.comap t inferInstance ≤ MeasurableSpace.comap (processCons x t) inferInstance :=
  calc MeasurableSpace.comap t inferInstance
      = MeasurableSpace.comap (processTail (processCons x t)) inferInstance := by
        rw [processTail_processCons]
    _ ≤ MeasurableSpace.comap (processCons x t) inferInstance := comap_processTail_le

end Probability

end TauCeti
