/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib.GroupTheory.Index
import Mathlib.GroupTheory.QuotientGroup.Basic
import Mathlib.Tactic

/-!
# The index of powers in a finitely generated commutative group

In a commutative group generated by a finite set `S`, the range of the `n`th-power
homomorphism has index at most `n ^ S.card` when `n` is nonzero: the quotient by the
`n`th powers is generated by the image of `S`, and every generator has order dividing `n`.

## Main results

* `TauCeti.index_powMonoidHom_range_le_of_closure_eq_top`: `[G : Gⁿ] ≤ n ^ S.card`.
* `TauCeti.index_powMonoidHom_two_range_le_of_closure_eq_top`: `[G : G²] ≤ 2 ^ S.card`.

## Provenance

The argument is migrated from
[kim-em/erdos-unit-distance](https://github.com/kim-em/erdos-unit-distance), where it was an
abstract step towards bounding the index of squares in the unit group of a number field.
-/

namespace TauCeti

/-- An element of a finitely generated commutative group is an integer-power product over any
finite generating set. -/
private theorem exists_finset_zpow_prod_of_mem_closure {G : Type*} [CommGroup G] {S : Finset G}
    {g : G} (hg : g ∈ Subgroup.closure (S : Set G)) :
    ∃ z : S → ℤ, g = ∏ s : S, (s : G) ^ z s := by
  classical
  induction hg using Subgroup.closure_induction with
  | mem x hx =>
      refine ⟨fun s => if s = ⟨x, hx⟩ then 1 else 0, ?_⟩
      rw [Finset.prod_eq_single (⟨x, hx⟩ : S)] <;> simp +contextual
  | one => exact ⟨0, by simp⟩
  | mul x y _ _ hx hy =>
      obtain ⟨zx, rfl⟩ := hx
      obtain ⟨zy, rfl⟩ := hy
      exact ⟨zx + zy, by simp [zpow_add, Finset.prod_mul_distrib]⟩
  | inv x _ hx =>
      obtain ⟨zx, rfl⟩ := hx
      exact ⟨-zx, by simp [zpow_neg, Finset.prod_inv_distrib]⟩

/-- In a commutative group generated by a finite set `S`, the range of `powMonoidHom n` has
index at most `n ^ S.card` when `n` is nonzero. The quotient by the `n`th powers is generated by
the image of `S`, with every generator having order dividing `n`. -/
theorem index_powMonoidHom_range_le_of_closure_eq_top {G : Type*} [CommGroup G] {S : Finset G}
    {n : ℕ} (hn : n ≠ 0) (hS : Subgroup.closure (S : Set G) = ⊤) :
    (powMonoidHom n : G →* G).range.index ≤ n ^ S.card := by
  classical
  set H := (powMonoidHom n : G →* G).range with hH
  set mk : G →* G ⧸ H := QuotientGroup.mk' H with hmk
  have hpow : ∀ g : G, ∃ z : S → ℤ, g = ∏ s : S, (s : G) ^ z s := by
    intro g
    have hg : g ∈ Subgroup.closure (S : Set G) := hS ▸ Subgroup.mem_top g
    exact exists_finset_zpow_prod_of_mem_closure hg
  have hpow_n : ∀ s : S, mk (s : G) ^ n = 1 := fun s => by
    rw [← map_pow, hmk, QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff]
    exact ⟨(s : G), rfl⟩
  have hsurj : Function.Surjective
      (fun f : S → Fin n => ∏ s : S, mk (s : G) ^ (f s : ℕ)) := by
    intro q
    obtain ⟨g, rfl⟩ := QuotientGroup.mk'_surjective H q
    obtain ⟨z, rfl⟩ := hpow g
    refine ⟨fun s => ⟨(z s % (n : ℤ)).toNat, ?_⟩, ?_⟩
    · rw [← Int.ofNat_lt, Int.toNat_of_nonneg (Int.emod_nonneg _ (Int.natCast_ne_zero.mpr hn))]
      exact Int.emod_lt_of_pos _ (Int.natCast_pos.mpr (Nat.pos_of_ne_zero hn))
    rw [hmk, map_prod]
    refine Finset.prod_congr rfl fun s _ => ?_
    rw [map_zpow, ← hmk]
    conv_rhs => rw [zpow_eq_zpow_emod' (z s) (hpow_n s)]
    rw [← zpow_natCast (mk (s : G)) (z s % (n : ℤ)).toNat,
      Int.toNat_of_nonneg (Int.emod_nonneg _ (Int.natCast_ne_zero.mpr hn))]
  calc (powMonoidHom n : G →* G).range.index
      = Nat.card (G ⧸ H) := rfl
    _ ≤ Nat.card (S → Fin n) := Nat.card_le_card_of_surjective _ hsurj
    _ = n ^ S.card := by
        rw [Nat.card_eq_fintype_card, Fintype.card_fun, Fintype.card_fin, Fintype.card_coe]

/-- In a commutative group generated by a finite set `S`, the range of the squaring
homomorphism `powMonoidHom 2` has index at most `2 ^ S.card`. The quotient by the squares is
an elementary abelian `2`-group spanned by the image of `S`. -/
theorem index_powMonoidHom_two_range_le_of_closure_eq_top {G : Type*} [CommGroup G]
    {S : Finset G} (hS : Subgroup.closure (S : Set G) = ⊤) :
    (powMonoidHom 2 : G →* G).range.index ≤ 2 ^ S.card :=
  index_powMonoidHom_range_le_of_closure_eq_top (by norm_num) hS

end TauCeti
