/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib.GroupTheory.Schreier
import Mathlib.Tactic

/-!
# Index bounds for power maps on groups

This file contains elementary index bounds for the ranges of positive-power maps on groups.

## Provenance

Migrated from
[kim-em/erdos-unit-distance](https://github.com/kim-em/erdos-unit-distance)
`ErdosUnitDistance/ClassNumber.lean`, the formalization of L. Alpöge's disproof of the
uniform-constant Erdős unit-distance conjecture.
-/

namespace TauCeti

/-- In a finitely generated commutative group, the range of the `n`th-power map has index at
most `n ^ Group.rank G`, for positive `n`. -/
theorem index_range_powMonoidHom_le_rank {G : Type*} [CommGroup G] [Group.FG G] {n : ℕ}
    (hn : 0 < n) :
    (powMonoidHom n : G →* G).range.index ≤ n ^ Group.rank G := by
  classical
  let H := (powMonoidHom n : G →* G).range
  have hpow : ∀ q : G ⧸ H, q ^ n = 1 := by
    intro q
    obtain ⟨g, rfl⟩ := QuotientGroup.mk'_surjective H q
    rw [← map_pow]
    exact (QuotientGroup.eq_one_iff (N := H) (g ^ n)).mpr ⟨g, rfl⟩
  have hcard : Nat.card (G ⧸ H) ≤ n ^ Group.rank (G ⧸ H) :=
    Nat.le_of_dvd (Nat.pow_pos hn) (card_dvd_exponent_pow_rank' (G := G ⧸ H) hpow)
  have hrank : Group.rank (G ⧸ H) ≤ Group.rank G :=
    Group.rank_le_of_surjective (QuotientGroup.mk' H) (QuotientGroup.mk'_surjective H)
  exact hcard.trans (Nat.pow_le_pow_right hn hrank)

/-- In a commutative group generated by a finite set `S`, the range of the `n`th-power map has
index at most `n ^ S.card`, for positive `n`. -/
theorem index_range_powMonoidHom_le_of_closure_eq_top {G : Type*} [CommGroup G]
    {S : Finset G} {n : ℕ} (hn : 0 < n) (hS : Subgroup.closure (S : Set G) = ⊤) :
    (powMonoidHom n : G →* G).range.index ≤ n ^ S.card := by
  classical
  haveI : Group.FG G := Group.fg_iff.mpr ⟨S, hS, S.finite_toSet⟩
  exact (index_range_powMonoidHom_le_rank (G := G) hn).trans
    (Nat.pow_le_pow_right hn (Group.rank_le hS))

/-- In a commutative group generated by a finite set `S`, the range of the squaring map has
index at most `2 ^ S.card`. -/
theorem index_range_powMonoidHom_two_le_of_closure_eq_top {G : Type*} [CommGroup G]
    {S : Finset G} (hS : Subgroup.closure (S : Set G) = ⊤) :
    (powMonoidHom 2 : G →* G).range.index ≤ 2 ^ S.card :=
  index_range_powMonoidHom_le_of_closure_eq_top (by norm_num) hS

end TauCeti
