/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib.GroupTheory.Schreier
import Mathlib.Tactic

/-!
# The index of powers in a finitely generated commutative group

In a commutative group generated by a finite set `S`, the range of the `n`th-power homomorphism
has index at most `n ^ S.card` when `n` is nonzero. In particular, the range of the squaring
homomorphism has index at most `2 ^ S.card`.

## Main results

* `TauCeti.index_powMonoidHom_range_le_of_closure_eq_top`: `[G : Gⁿ] ≤ n ^ S.card`.
* `TauCeti.index_powMonoidHom_two_range_le_of_closure_eq_top`: `[G : G²] ≤ 2 ^ S.card`.

## Provenance

The argument is migrated from
[kim-em/erdos-unit-distance](https://github.com/kim-em/erdos-unit-distance), where it was an
abstract step towards bounding the index of squares in the unit group of a number field.
-/

namespace TauCeti

/-- In a commutative group generated by a finite set `S`, the range of `powMonoidHom n` has
index at most `n ^ S.card` when `n` is nonzero. This applies Mathlib's exponent/rank cardinality
bound to the quotient by the `n`th powers. -/
theorem index_powMonoidHom_range_le_of_closure_eq_top {G : Type*} [CommGroup G]
    {S : Finset G} {n : ℕ} (hn : n ≠ 0) (hS : Subgroup.closure (S : Set G) = ⊤) :
    (powMonoidHom n : G →* G).range.index ≤ n ^ S.card := by
  classical
  set H := (powMonoidHom n : G →* G).range with hH
  haveI : Group.FG G := Group.fg_iff'.mpr ⟨S.card, S, rfl, hS⟩
  haveI : Group.FG (G ⧸ H) := Group.fg_of_surjective (QuotientGroup.mk'_surjective H)
  have hpow : ∀ q : G ⧸ H, q ^ n = 1 := fun q =>
    QuotientGroup.induction_on q fun g => by
      rw [← QuotientGroup.mk_pow, QuotientGroup.eq_one_iff]
      exact ⟨g, rfl⟩
  have hcard : Nat.card (G ⧸ H) ∣ n ^ Group.rank (G ⧸ H) :=
    card_dvd_exponent_pow_rank' (G ⧸ H) hpow
  have hrank : Group.rank (G ⧸ H) ≤ S.card :=
    (Group.rank_le_of_surjective (QuotientGroup.mk' H) (QuotientGroup.mk'_surjective H)).trans
      (Group.rank_le hS)
  calc (powMonoidHom n : G →* G).range.index
      = Nat.card (G ⧸ H) := rfl
    _ ≤ n ^ Group.rank (G ⧸ H) := Nat.le_of_dvd (pow_pos (Nat.pos_of_ne_zero hn) _) hcard
    _ ≤ n ^ S.card := Nat.pow_le_pow_right (Nat.pos_of_ne_zero hn) hrank

/-- In a commutative group generated by a finite set `S`, the range of the squaring
homomorphism `powMonoidHom 2` has index at most `2 ^ S.card`. The quotient by the squares is
an elementary abelian `2`-group spanned by the image of `S`. -/
theorem index_powMonoidHom_two_range_le_of_closure_eq_top {G : Type*} [CommGroup G]
    {S : Finset G} (hS : Subgroup.closure (S : Set G) = ⊤) :
    (powMonoidHom 2 : G →* G).range.index ≤ 2 ^ S.card :=
  index_powMonoidHom_range_le_of_closure_eq_top (by norm_num) hS

end TauCeti
