-- This is the AI-owned root of the TauCeti mathematics library.
--
-- Everything reachable from here must be sorry-free, and must not import
-- `TauCetiRoadmap` or `TauCetiReview` (both enforced in CI).
--
-- This import list is generated by `Scripts/mk_all.sh` (every `TauCeti/` module,
-- sorted); CI keeps it in sync. Do not edit it by hand.
import TauCeti.Algebra.AlgebraicGroup.AdditiveGroup
import TauCeti.Algebra.AlgebraicGroup.BaseChange
import TauCeti.Algebra.AlgebraicGroup.CommHopfAlgCat
import TauCeti.Algebra.AlgebraicGroup.DiagonalizableGroup
import TauCeti.Algebra.AlgebraicGroup.FiniteTypeCommHopfAlgCat
import TauCeti.Algebra.AlgebraicGroup.FunctorOfPoints
import TauCeti.Algebra.AlgebraicGroup.HopfMap
import TauCeti.Algebra.AlgebraicGroup.MultiplicativeGroup
import TauCeti.Algebra.AlgebraicGroup.PointsFunctor
import TauCeti.Algebra.AlgebraicGroup.Product
import TauCeti.Algebra.Bialgebra.TensorProduct
import TauCeti.Algebra.Coalgebra.Comodule
import TauCeti.Algebra.Coalgebra.Comodule.Cofree
import TauCeti.Algebra.Coalgebra.Comodule.Corestrict
import TauCeti.Algebra.Coalgebra.Comodule.Finite
import TauCeti.Algebra.Coalgebra.Comodule.FiniteCofree
import TauCeti.Algebra.Coalgebra.Comodule.FiniteCorestrict
import TauCeti.Algebra.Coalgebra.Comodule.FinitePreadditive
import TauCeti.Algebra.Coalgebra.Comodule.FiniteTrivial
import TauCeti.Algebra.Coalgebra.Comodule.Hom
import TauCeti.Algebra.Coalgebra.Comodule.MatrixCoefficient
import TauCeti.Algebra.Coalgebra.Comodule.MatrixCoefficientAdjoin
import TauCeti.Algebra.Coalgebra.Comodule.MatrixCoefficientFunctorial
import TauCeti.Algebra.Coalgebra.Comodule.MatrixCoefficientRegular
import TauCeti.Algebra.Coalgebra.Comodule.MatrixCoefficientTrivial
import TauCeti.Algebra.Coalgebra.Comodule.Preadditive
import TauCeti.Algebra.Coalgebra.Comodule.Regular
import TauCeti.Algebra.Coalgebra.Comodule.Transport
import TauCeti.Algebra.Coalgebra.Comodule.Trivial
import TauCeti.Algebra.Coalgebra.Comodule.Zero
import TauCeti.Algebra.Coalgebra.ComoduleCat
import TauCeti.Algebra.Coalgebra.Subcoalgebra
import TauCeti.Algebra.Coalgebra.Subcoalgebra.GroupLike
import TauCeti.Algebra.Coalgebra.Subcoalgebra.Lattice
import TauCeti.Algebra.Coalgebra.Subcoalgebra.Map
import TauCeti.Algebra.Coalgebra.Subcoalgebra.RegularSubcomodule
import TauCeti.Algebra.Coalgebra.Subcomodule
import TauCeti.Algebra.Coalgebra.Subcomodule.Lattice
import TauCeti.Algebra.Group.PowMonoidHom
import TauCeti.Algebra.HopfAlgebra
import TauCeti.Algebra.HopfAlgebra.HopfIdeal
import TauCeti.Algebra.HopfAlgebra.Quotient
import TauCeti.Algebra.HopfAlgebra.SymmetricAlgebra
import TauCeti.AlgebraicGeometry.WeilDivisor
import TauCeti.AlgebraicTopology.UniversalCover.Deck
import TauCeti.AlgebraicTopology.UniversalCover.Deck.Conjugation
import TauCeti.AlgebraicTopology.UniversalCover.Deck.Connected
import TauCeti.AlgebraicTopology.UniversalCover.Deck.Fiber
import TauCeti.AlgebraicTopology.UniversalCover.Deck.FiberOrbit
import TauCeti.AlgebraicTopology.UniversalCover.Deck.FiberTransport
import TauCeti.AlgebraicTopology.UniversalCover.Deck.Quotient
import TauCeti.AlgebraicTopology.UniversalCover.Deck.Regular
import TauCeti.Analysis.PDE.LowerOrder
import TauCeti.Analysis.PDE.UniformEllipticity
import TauCeti.Basic
import TauCeti.FieldTheory.IntermediateField.Quadratic
import TauCeti.FieldTheory.Trace
import TauCeti.NumberTheory.DedekindDomain.RamificationInertia
import TauCeti.NumberTheory.DedekindDomain.Transversal
import TauCeti.NumberTheory.EffectiveBounds.ClassNumber
import TauCeti.NumberTheory.EffectiveBounds.Discriminant
import TauCeti.NumberTheory.EffectiveBounds.IdealCount
import TauCeti.NumberTheory.EffectiveBounds.UnitSquares
import TauCeti.NumberTheory.Multiquadratic.Degree
import TauCeti.NumberTheory.Multiquadratic.Galois
import TauCeti.NumberTheory.Multiquadratic.GaloisGroup
import TauCeti.NumberTheory.Multiquadratic.SquareClass
import TauCeti.NumberTheory.NumberField.MultiquadraticSplitting
import TauCeti.NumberTheory.NumberField.QuadraticSplitting
import TauCeti.NumberTheory.NumberField.SplitsCompletely
import TauCeti.Topology.Algebra.HomeomorphAction
