/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib.Algebra.Algebra.Subalgebra.Lattice
import Mathlib.LinearAlgebra.Span.Defs
import TauCeti.Algebra.Coalgebra.Comodule.MatrixCoefficient

/-!
# Subobjects generated by matrix coefficients

This file packages the linear span and algebra generated by the matrix coefficients of a
right comodule. These are the bookkeeping objects needed to state the faithful-representation
criterion in the reductive-groups roadmap: for an affine group scheme represented by a Hopf
algebra `A`, a representation is faithful exactly when its matrix coefficients generate `A`.

## Main definitions

* `TauCeti.Comodule.matrixCoefficientSet`: the set of all matrix coefficients of a comodule.
* `TauCeti.Comodule.matrixCoefficientSubmodule`: the `R`-submodule spanned by those
  coefficients.
* `TauCeti.Comodule.matrixCoefficientSubalgebra`: the `R`-subalgebra generated by those
  coefficients when the coalgebra is also an `R`-algebra.

## References

This is standard coalgebra/comodule terminology; see Sweedler, *Hopf Algebras*, Chapter 2.
It supplies a prerequisite for `TauCetiRoadmap/ReductiveGroups/README.md`, Layer 1,
"Faithfulness done right", where faithful representations are characterized by their matrix
coefficients generating the coordinate Hopf algebra.
-/

namespace TauCeti

namespace Comodule

universe u v w

variable {R : Type u} {C : Type v} {M : Type w}

section Submodule

variable [CommSemiring R]
variable [AddCommMonoid C] [Module R C] [Coalgebra R C]
variable [AddCommMonoid M] [Module R M] [Comodule R C M]

/-- The set of all matrix coefficients of a right comodule. -/
def matrixCoefficientSet : Set C :=
  Set.range (Function.uncurry (matrixCoefficient (R := R) (C := C) (M := M)))

/-- The matrix coefficient set is the range of the uncurried matrix coefficient map. -/
theorem matrixCoefficientSet_def :
    matrixCoefficientSet (R := R) (C := C) (M := M) =
      Set.range (Function.uncurry (matrixCoefficient (R := R) (C := C) (M := M))) :=
  rfl

/-- A matrix coefficient belongs to the set of all matrix coefficients. -/
@[simp]
theorem matrixCoefficient_mem_set (φ : M →ₗ[R] R) (m : M) :
    matrixCoefficient (R := R) (C := C) φ m ∈
      matrixCoefficientSet (R := R) (C := C) (M := M) :=
  ⟨(φ, m), rfl⟩

/-- Membership in the set of matrix coefficients is the existence of a functional and a
vector giving the element. -/
theorem mem_matrixCoefficientSet_iff (c : C) :
    c ∈ matrixCoefficientSet (R := R) (C := C) (M := M) ↔
      ∃ (φ : M →ₗ[R] R) (m : M), matrixCoefficient (R := R) (C := C) φ m = c := by
  constructor
  · rintro ⟨⟨φ, m⟩, rfl⟩
    exact ⟨φ, m, rfl⟩
  · rintro ⟨φ, m, rfl⟩
    exact matrixCoefficient_mem_set (R := R) (C := C) φ m

/-- The `R`-submodule spanned by all matrix coefficients of a right comodule. -/
def matrixCoefficientSubmodule : Submodule R C :=
  Submodule.span R (matrixCoefficientSet (R := R) (C := C) (M := M))

/-- The matrix coefficient submodule is the span of the matrix coefficient set. -/
theorem matrixCoefficientSubmodule_def :
    matrixCoefficientSubmodule (R := R) (C := C) (M := M) =
      Submodule.span R (matrixCoefficientSet (R := R) (C := C) (M := M)) :=
  rfl

/-- A matrix coefficient belongs to the submodule spanned by all matrix coefficients. -/
@[simp]
theorem matrixCoefficient_mem_submodule (φ : M →ₗ[R] R) (m : M) :
    matrixCoefficient (R := R) (C := C) φ m ∈
      matrixCoefficientSubmodule (R := R) (C := C) (M := M) :=
  Submodule.subset_span (matrixCoefficient_mem_set (R := R) (C := C) φ m)

/-- The coefficient submodule is the smallest submodule containing all matrix coefficients. -/
theorem matrixCoefficientSubmodule_le {P : Submodule R C}
    (hP : ∀ (φ : M →ₗ[R] R) (m : M), matrixCoefficient (R := R) (C := C) φ m ∈ P) :
    matrixCoefficientSubmodule (R := R) (C := C) (M := M) ≤ P := by
  rw [matrixCoefficientSubmodule, Submodule.span_le]
  intro c hc
  rcases (mem_matrixCoefficientSet_iff (R := R) (C := C) (M := M) c).mp hc with ⟨φ, m, rfl⟩
  exact hP φ m

/-- The coefficient submodule is contained in a submodule iff that submodule contains each
matrix coefficient. -/
theorem matrixCoefficientSubmodule_le_iff {P : Submodule R C} :
    matrixCoefficientSubmodule (R := R) (C := C) (M := M) ≤ P ↔
      ∀ (φ : M →ₗ[R] R) (m : M), matrixCoefficient (R := R) (C := C) φ m ∈ P :=
  ⟨fun hP φ m => hP (matrixCoefficient_mem_submodule (R := R) (C := C) φ m),
    matrixCoefficientSubmodule_le (R := R) (C := C) (M := M)⟩

end Submodule

section Algebra

variable [CommSemiring R]
variable [Semiring C] [Algebra R C]
variable [Coalgebra R C]
variable [AddCommMonoid M] [Module R M] [Comodule R C M]

/-- The `R`-subalgebra generated by all matrix coefficients of a right comodule.

For a Hopf algebra coordinate ring, the faithful-representation criterion will ask whether
this subalgebra is `⊤`. -/
def matrixCoefficientSubalgebra : Subalgebra R C :=
  Algebra.adjoin R (matrixCoefficientSet (R := R) (C := C) (M := M))

/-- The matrix coefficient subalgebra is the algebra generated by the matrix coefficient set. -/
theorem matrixCoefficientSubalgebra_def :
    matrixCoefficientSubalgebra (R := R) (C := C) (M := M) =
      Algebra.adjoin R (matrixCoefficientSet (R := R) (C := C) (M := M)) :=
  rfl

/-- A matrix coefficient belongs to the algebra generated by all matrix coefficients. -/
@[simp]
theorem matrixCoefficient_mem_subalgebra (φ : M →ₗ[R] R) (m : M) :
    matrixCoefficient (R := R) (C := C) φ m ∈
      matrixCoefficientSubalgebra (R := R) (C := C) (M := M) :=
  Algebra.subset_adjoin (matrixCoefficient_mem_set (R := R) (C := C) φ m)

/-- The coefficient algebra is the smallest subalgebra containing all matrix coefficients. -/
theorem matrixCoefficientSubalgebra_le {S : Subalgebra R C}
    (hS : ∀ (φ : M →ₗ[R] R) (m : M), matrixCoefficient (R := R) (C := C) φ m ∈ S) :
    matrixCoefficientSubalgebra (R := R) (C := C) (M := M) ≤ S := by
  rw [matrixCoefficientSubalgebra, Algebra.adjoin_le_iff]
  intro c hc
  rcases (mem_matrixCoefficientSet_iff (R := R) (C := C) (M := M) c).mp hc with ⟨φ, m, rfl⟩
  exact hS φ m

/-- The coefficient algebra is contained in a subalgebra iff that subalgebra contains each
matrix coefficient. -/
theorem matrixCoefficientSubalgebra_le_iff {S : Subalgebra R C} :
    matrixCoefficientSubalgebra (R := R) (C := C) (M := M) ≤ S ↔
      ∀ (φ : M →ₗ[R] R) (m : M), matrixCoefficient (R := R) (C := C) φ m ∈ S :=
  ⟨fun hS φ m => hS (matrixCoefficient_mem_subalgebra (R := R) (C := C) φ m),
    matrixCoefficientSubalgebra_le (R := R) (C := C) (M := M)⟩

/-- If the matrix coefficients linearly span the coalgebra, then they generate the ambient
algebra. -/
theorem matrixCoefficientSubalgebra_eq_top_of_submodule_eq_top
    (h : matrixCoefficientSubmodule (R := R) (C := C) (M := M) = ⊤) :
    matrixCoefficientSubalgebra (R := R) (C := C) (M := M) = ⊤ := by
  rw [matrixCoefficientSubalgebra, ← Algebra.toSubmodule_eq_top]
  exact top_le_iff.mp <| by
    rw [← h, matrixCoefficientSubmodule]
    exact Algebra.span_le_adjoin R (matrixCoefficientSet (R := R) (C := C) (M := M))

end Algebra

end Comodule

end TauCeti
