/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import TauCeti.Algebra.Coalgebra.Comodule.Hom
import TauCeti.Algebra.Coalgebra.Comodule.Trivial

/-!
# Matrix coefficients of comodules

For a right comodule `M` over a coalgebra `C`, a linear functional `φ : M →ₗ[R] R` and a
vector `m : M` define a coefficient element of `C` by applying `φ` to the vector component
of the coaction:

`cᵩ,ₘ = (R ⊗ C ≃ C) ((φ ⊗ id) (ρ m))`.

These coefficients are the coalgebra-side functions attached to a representation. They are
the named ingredient in the reductive-groups roadmap's representation/comodule dictionary,
and later faithful-representation criteria ask for the subalgebra generated by such matrix
coefficients.

## Main definitions

* `TauCeti.Comodule.matrixCoefficientLinear`: the linear map `M →ₗ[R] C` attached to a
  functional `φ : M →ₗ[R] R`.
* `TauCeti.Comodule.matrixCoefficient`: the coefficient element attached to `φ` and `m`.
* `TauCeti.Comodule.matrixCoefficientBilinear`: bilinearity in the functional and vector.

## References

This is standard coalgebra/comodule terminology; see Sweedler, *Hopf Algebras*, Chapter 2.
It supplies the "matrix coefficients" prerequisite in
`ReductiveGroups/README.md` in TauCetiRoadmap, Layer 1, "The dictionary: representation of
`G` ⇆ `A`-comodule; matrix coefficients."
-/

open scoped TensorProduct

namespace TauCeti

namespace Comodule

universe u v w x

variable {R : Type u} {C : Type v} {M : Type w} {N : Type x}
variable [CommSemiring R]
variable [AddCommMonoid C] [Module R C] [Coalgebra R C]
variable [AddCommMonoid M] [Module R M] [Comodule R C M]
variable [AddCommMonoid N] [Module R N] [Comodule R C N]

/-- The linear map of matrix coefficients associated to a functional on a right comodule.

It sends `m : M` to `(φ ⊗ id) (ρ m)`, with the canonical identification `R ⊗ C ≃ C`. -/
def matrixCoefficientLinear (φ : M →ₗ[R] R) : M →ₗ[R] C :=
  (TensorProduct.lid R C).toLinearMap.comp
    ((TensorProduct.map φ LinearMap.id).comp (coact (R := R) (C := C) (M := M)))

/-- The matrix coefficient attached to a functional and a vector in a right comodule. -/
def matrixCoefficient (φ : M →ₗ[R] R) (m : M) : C :=
  matrixCoefficientLinear (R := R) (C := C) φ m

@[simp]
theorem matrixCoefficientLinear_apply (φ : M →ₗ[R] R) (m : M) :
    matrixCoefficientLinear (R := R) (C := C) φ m = matrixCoefficient (R := R) (C := C) φ m :=
  rfl

/-- Matrix coefficients are obtained by applying `φ ⊗ id` to the coaction. -/
theorem matrixCoefficient_def (φ : M →ₗ[R] R) (m : M) :
    matrixCoefficient (R := R) (C := C) φ m =
      TensorProduct.lid R C
        (TensorProduct.map φ LinearMap.id (coact (R := R) (C := C) (M := M) m)) :=
  rfl

@[deprecated matrixCoefficient_def (since := "2026-06-19")]
alias matrixCoefficient_eq_lid_map_coact := matrixCoefficient_def

@[simp]
theorem matrixCoefficient_zero (φ : M →ₗ[R] R) :
    matrixCoefficient (R := R) (C := C) φ 0 = 0 :=
  map_zero (matrixCoefficientLinear (R := R) (C := C) φ)

@[simp]
theorem matrixCoefficient_add (φ : M →ₗ[R] R) (m n : M) :
    matrixCoefficient (R := R) (C := C) φ (m + n) =
      matrixCoefficient (R := R) (C := C) φ m +
        matrixCoefficient (R := R) (C := C) φ n :=
  map_add (matrixCoefficientLinear (R := R) (C := C) φ) m n

@[simp]
theorem matrixCoefficient_smul (φ : M →ₗ[R] R) (r : R) (m : M) :
    matrixCoefficient (R := R) (C := C) φ (r • m) =
      r • matrixCoefficient (R := R) (C := C) φ m :=
  map_smul (matrixCoefficientLinear (R := R) (C := C) φ) r m

/-- Matrix coefficients as a linear map from the dual module to linear maps `M →ₗ[R] C`. -/
def matrixCoefficientBilinear : (M →ₗ[R] R) →ₗ[R] M →ₗ[R] C where
  toFun := matrixCoefficientLinear (R := R) (C := C) (M := M)
  map_add' φ ψ := by
    ext m
    simp [matrixCoefficientLinear, TensorProduct.map_add_left]
  map_smul' r φ := by
    ext m
    simp [matrixCoefficientLinear, TensorProduct.map_smul_left]

@[simp]
theorem matrixCoefficientBilinear_apply (φ : M →ₗ[R] R) :
    matrixCoefficientBilinear (R := R) (C := C) (M := M) φ =
      matrixCoefficientLinear (R := R) (C := C) φ :=
  rfl

@[simp]
theorem matrixCoefficientBilinear_apply_apply (φ : M →ₗ[R] R) (m : M) :
    matrixCoefficientBilinear (R := R) (C := C) (M := M) φ m =
      matrixCoefficient (R := R) (C := C) φ m :=
  rfl

@[simp]
theorem matrixCoefficient_zero_functional (m : M) :
    matrixCoefficient (R := R) (C := C) (0 : M →ₗ[R] R) m = 0 := by
  simp [matrixCoefficient_def]

@[simp]
theorem matrixCoefficient_add_functional (φ ψ : M →ₗ[R] R) (m : M) :
    matrixCoefficient (R := R) (C := C) (φ + ψ) m =
      matrixCoefficient (R := R) (C := C) φ m +
        matrixCoefficient (R := R) (C := C) ψ m := by
  simp [matrixCoefficient_def, TensorProduct.map_add_left]

@[simp]
theorem matrixCoefficient_smul_functional (r : R) (φ : M →ₗ[R] R) (m : M) :
    matrixCoefficient (R := R) (C := C) (r • φ) m =
      r • matrixCoefficient (R := R) (C := C) φ m := by
  simp [matrixCoefficient_def, TensorProduct.map_smul_left]

/-- Matrix coefficients are natural in comodule morphisms: pushing the vector forward is
the same as pulling the functional back. -/
@[simp]
theorem matrixCoefficient_map (f : Hom R C M N) (φ : N →ₗ[R] R) (m : M) :
    matrixCoefficient (R := R) (C := C) φ (f m) =
      matrixCoefficient (R := R) (C := C) (φ.comp f.toLinearMap) m := by
  rw [matrixCoefficient_def, matrixCoefficient_def,
    ← Hom.map_coact_apply f m]
  exact congrArg (TensorProduct.lid R C)
    (TensorProduct.map_map φ LinearMap.id f.toLinearMap LinearMap.id
      (coact (R := R) (C := C) (M := M) m))

/-- For the regular comodule, the coefficient attached to the counit is the identity map. -/
@[simp]
theorem matrixCoefficient_counit_self (c : C) :
    matrixCoefficient (R := R) (C := C) (M := C) (Coalgebra.counit (R := R) (A := C)) c = c := by
  simpa [matrixCoefficient_def, LinearMap.rTensor] using
    congrArg (TensorProduct.lid R C) (Coalgebra.rTensor_counit_comul (R := R) (A := C) c)

section GroupLike

variable {M : Type w} [AddCommMonoid M] [Module R M]

/-- Matrix coefficients of a group-like comodule are scalar multiples of the group-like
element. -/
@[simp]
theorem matrixCoefficient_groupLike (g : GroupLike R C) (φ : M →ₗ[R] R) (m : M) :
    letI : Comodule R C M := groupLike (R := R) (C := C) (M := M) g
    matrixCoefficient (R := R) (C := C) φ m = φ m • (g : C) := by
  letI : Comodule R C M := groupLike (R := R) (C := C) (M := M) g
  simp [matrixCoefficient_def]

end GroupLike

section Trivial

variable {C : Type v} [Semiring C] [Bialgebra R C]
variable {M : Type w} [AddCommMonoid M] [Module R M]

attribute [local instance] trivial

/-- Matrix coefficients of the trivial comodule are scalar multiples of `1`. -/
@[simp]
theorem matrixCoefficient_trivial (φ : M →ₗ[R] R) (m : M) :
    matrixCoefficient (R := R) (C := C) φ m = φ m • (1 : C) := by
  simp

end Trivial

end Comodule

end TauCeti
