/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import TauCeti.Algebra.Coalgebra.Comodule.MatrixCoefficientAdjoin

/-!
# Matrix coefficients of group-like and trivial comodules

This file packages the generated coefficient objects for group-like and trivial comodules.
The group-like results hold over coalgebras, with algebra-generation statements requiring only
an ambient compatible algebra structure. The individual coefficient calculations are already in
`TauCeti.Algebra.Coalgebra.Comodule.MatrixCoefficient`: if `M` has a group-like coaction
attached to `g`, then every coefficient is a scalar multiple of `g`, and for the trivial
coaction every coefficient is a scalar multiple of `1`.

Here we record the corresponding span and algebra-generation consequences. For an arbitrary
group-like module, its coefficient submodule is contained in the line spanned by `g`, and for
the rank-one group-like comodule `R`, this inclusion is an equality. The corresponding
coefficient subalgebra is contained in the subalgebra generated by `g`, and is exactly that
subalgebra for the rank-one group-like comodule. Specializing directly to the trivial
coefficient calculation, a trivial comodule's coefficient subalgebra is the bottom
`R`-subalgebra.

This is Layer 1 infrastructure for the reductive-groups roadmap target "Faithfulness done
right": the faithful-representation criterion is stated in terms of the algebra generated by
matrix coefficients, and the tensor-unit/trivial representation should have the expected
coefficient algebra.

## Main declarations

* `TauCeti.Comodule.groupLike_matrixCoefficientSubmodule_le_span_singleton`.
* `TauCeti.Comodule.groupLike_rankOne_matrixCoefficientSubmodule_eq_span_singleton`.
* `TauCeti.Comodule.groupLike_matrixCoefficientSubalgebra_le_adjoin_singleton`.
* `TauCeti.Comodule.groupLike_rankOne_matrixCoefficientSubalgebra_eq_adjoin_singleton`.
* `TauCeti.Comodule.trivial_rankOne_matrixCoefficientSubmodule_eq_span_singleton_one`.
* `TauCeti.Comodule.trivial_matrixCoefficientSubalgebra_le_bot`.
* `TauCeti.Comodule.trivial_matrixCoefficientSubalgebra_eq_bot`.

## References

These are the standard coefficient calculations for group-like and trivial comodules, using
the existing Tau Ceti matrix-coefficient API and Mathlib's `Algebra.adjoin`/`Submodule.span`
API.
-/

namespace TauCeti

namespace Comodule

universe u v w

variable {R : Type u} {C : Type v}
variable [CommSemiring R]

section GroupLikeSubmodule

variable [AddCommMonoid C] [Module R C] [Coalgebra R C]
variable {M : Type w} [AddCommMonoid M] [Module R M]

/-- A matrix coefficient of a group-like comodule lies in the line spanned by its group-like
element. -/
theorem groupLike_matrixCoefficient_mem_span_singleton (g : GroupLike R C) (φ : M →ₗ[R] R)
    (m : M) :
    letI : Comodule R C M := groupLike (R := R) (C := C) (M := M) g
    matrixCoefficient (R := R) (C := C) φ m ∈ Submodule.span R ({(g : C)} : Set C) := by
  letI : Comodule R C M := groupLike (R := R) (C := C) (M := M) g
  rw [matrixCoefficient_groupLike]
  exact Submodule.smul_mem _ _ (Submodule.subset_span (Set.mem_singleton (g : C)))

/-- The coefficient submodule of a group-like comodule is contained in the line spanned by its
group-like element. -/
theorem groupLike_matrixCoefficientSubmodule_le_span_singleton (g : GroupLike R C) :
    letI : Comodule R C M := groupLike (R := R) (C := C) (M := M) g
    matrixCoefficientSubmodule (R := R) (C := C) (M := M) ≤
      Submodule.span R ({(g : C)} : Set C) := by
  letI : Comodule R C M := groupLike (R := R) (C := C) (M := M) g
  exact matrixCoefficientSubmodule_le (R := R) (C := C) (M := M)
    (groupLike_matrixCoefficient_mem_span_singleton (R := R) (C := C) g)

/-- The group-like element is a matrix coefficient of the rank-one group-like comodule. -/
theorem groupLike_mem_rankOne_matrixCoefficientSet (g : GroupLike R C) :
    letI : Comodule R C R := groupLike (R := R) (C := C) (M := R) g
    (g : C) ∈ matrixCoefficientSet (R := R) (C := C) (M := R) := by
  letI : Comodule R C R := groupLike (R := R) (C := C) (M := R) g
  rw [mem_matrixCoefficientSet_iff]
  exact ⟨LinearMap.id, 1, by simp⟩

/-- The coefficient set of the rank-one group-like comodule spans exactly the line generated
by its group-like element. -/
@[simp]
theorem groupLike_rankOne_matrixCoefficientSubmodule_eq_span_singleton
    (g : GroupLike R C) :
    letI : Comodule R C R := groupLike (R := R) (C := C) (M := R) g
    matrixCoefficientSubmodule (R := R) (C := C) (M := R) =
      Submodule.span R ({(g : C)} : Set C) := by
  letI : Comodule R C R := groupLike (R := R) (C := C) (M := R) g
  apply le_antisymm
  · exact groupLike_matrixCoefficientSubmodule_le_span_singleton (R := R) (C := C)
      (M := R) g
  · rw [Submodule.span_le]
    intro c hc
    rw [Set.mem_singleton_iff.mp hc]
    exact Submodule.subset_span (groupLike_mem_rankOne_matrixCoefficientSet (R := R)
      (C := C) g)

end GroupLikeSubmodule

section GroupLikeSubalgebra

variable [Semiring C] [Algebra R C] [Coalgebra R C]
variable {M : Type w} [AddCommMonoid M] [Module R M]

/-- A matrix coefficient of a group-like comodule lies in the subalgebra generated by its
group-like element. -/
theorem groupLike_matrixCoefficient_mem_adjoin_singleton (g : GroupLike R C) (φ : M →ₗ[R] R)
    (m : M) :
    letI : Comodule R C M := groupLike (R := R) (C := C) (M := M) g
    matrixCoefficient (R := R) (C := C) φ m ∈ Algebra.adjoin R ({(g : C)} : Set C) := by
  letI : Comodule R C M := groupLike (R := R) (C := C) (M := M) g
  rw [matrixCoefficient_groupLike]
  exact (Algebra.adjoin R ({(g : C)} : Set C)).smul_mem
    (Algebra.self_mem_adjoin_singleton R (g : C)) (φ m)

/-- The coefficient algebra of a group-like comodule is contained in the subalgebra generated
by its group-like element. -/
theorem groupLike_matrixCoefficientSubalgebra_le_adjoin_singleton (g : GroupLike R C) :
    letI : Comodule R C M := groupLike (R := R) (C := C) (M := M) g
    matrixCoefficientSubalgebra (R := R) (C := C) (M := M) ≤
      Algebra.adjoin R ({(g : C)} : Set C) := by
  letI : Comodule R C M := groupLike (R := R) (C := C) (M := M) g
  exact matrixCoefficientSubalgebra_le (R := R) (C := C) (M := M)
    (groupLike_matrixCoefficient_mem_adjoin_singleton (R := R) (C := C) g)

/-- The coefficient algebra of the rank-one group-like comodule is exactly the subalgebra
generated by its group-like element. -/
@[simp]
theorem groupLike_rankOne_matrixCoefficientSubalgebra_eq_adjoin_singleton
    (g : GroupLike R C) :
    letI : Comodule R C R := groupLike (R := R) (C := C) (M := R) g
    matrixCoefficientSubalgebra (R := R) (C := C) (M := R) =
      Algebra.adjoin R ({(g : C)} : Set C) := by
  letI : Comodule R C R := groupLike (R := R) (C := C) (M := R) g
  apply le_antisymm
  · exact groupLike_matrixCoefficientSubalgebra_le_adjoin_singleton (R := R) (C := C)
      (M := R) g
  · rw [Algebra.adjoin_le_iff]
    intro c hc
    rw [Set.mem_singleton_iff.mp hc]
    exact Algebra.subset_adjoin (groupLike_mem_rankOne_matrixCoefficientSet (R := R)
      (C := C) g)

end GroupLikeSubalgebra

section Arbitrary

variable [Semiring C] [Bialgebra R C]
variable {M : Type w} [AddCommMonoid M] [Module R M]

attribute [local instance] trivial

/-- A matrix coefficient of a trivial comodule lies in the line spanned by `1`. -/
theorem trivial_matrixCoefficient_mem_span_singleton_one (φ : M →ₗ[R] R) (m : M) :
    matrixCoefficient (R := R) (C := C) φ m ∈ Submodule.span R ({1} : Set C) := by
  rw [matrixCoefficient_trivial]
  exact Submodule.smul_mem _ _ (Submodule.subset_span (Set.mem_singleton (1 : C)))

/-- The coefficient submodule of a trivial comodule is contained in the line spanned by `1`. -/
theorem trivial_matrixCoefficientSubmodule_le_span_singleton_one :
    matrixCoefficientSubmodule (R := R) (C := C) (M := M) ≤
      Submodule.span R ({1} : Set C) :=
  matrixCoefficientSubmodule_le (R := R) (C := C) (M := M)
    trivial_matrixCoefficient_mem_span_singleton_one

/-- The coefficient submodule of the rank-one trivial comodule is exactly the line spanned by
`1`. -/
@[simp]
theorem trivial_rankOne_matrixCoefficientSubmodule_eq_span_singleton_one :
    matrixCoefficientSubmodule (R := R) (C := C) (M := R) =
      Submodule.span R ({1} : Set C) := by
  apply le_antisymm
  · exact trivial_matrixCoefficientSubmodule_le_span_singleton_one (R := R) (C := C)
      (M := R)
  · rw [Submodule.span_le]
    intro c hc
    rw [Set.mem_singleton_iff.mp hc]
    exact Submodule.subset_span <| by
      rw [mem_matrixCoefficientSet_iff]
      exact ⟨LinearMap.id, 1, by simp⟩

/-- A matrix coefficient of a trivial comodule lies in the bottom `R`-subalgebra. -/
theorem trivial_matrixCoefficient_mem_bot (φ : M →ₗ[R] R) (m : M) :
    matrixCoefficient (R := R) (C := C) φ m ∈ (⊥ : Subalgebra R C) := by
  rw [matrixCoefficient_trivial]
  exact (⊥ : Subalgebra R C).smul_mem (Subalgebra.one_mem _) (φ m)

/-- The coefficient algebra of a trivial comodule is contained in the bottom subalgebra. -/
theorem trivial_matrixCoefficientSubalgebra_le_bot :
    matrixCoefficientSubalgebra (R := R) (C := C) (M := M) ≤ ⊥ :=
  matrixCoefficientSubalgebra_le (R := R) (C := C) (M := M)
    trivial_matrixCoefficient_mem_bot

/-- The coefficient algebra of a trivial comodule is the bottom `R`-subalgebra. -/
@[simp]
theorem trivial_matrixCoefficientSubalgebra_eq_bot :
    matrixCoefficientSubalgebra (R := R) (C := C) (M := M) = ⊥ :=
  le_antisymm trivial_matrixCoefficientSubalgebra_le_bot bot_le

end Arbitrary

end Comodule

end TauCeti
