/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import TauCeti.Algebra.Coalgebra.Comodule.MatrixCoefficientAdjoin
import TauCeti.Algebra.Coalgebra.Comodule.Product

/-!
# Matrix coefficients of product comodules

This file records how matrix coefficients behave for the direct-sum/product comodule.  If
`M × N` carries `Comodule.Prod`, a coefficient of a vector `(m, n)` is the sum of the
corresponding left and right coefficients.  Consequently the coefficient submodule, and in
an algebra the coefficient subalgebra, generated by `M × N` is the supremum of the two
objects generated by `M` and by `N`.

This is a small Layer 1 prerequisite for the reductive-groups roadmap: matrix coefficients
are the coalgebra-side functions attached to representations, and the finite-dimensional
representation category needs their behavior under finite direct sums.

## Main results

* `TauCeti.Comodule.matrixCoefficient_prod`: coefficient formula for `M × N`.
* `TauCeti.Comodule.matrixCoefficientSubmodule_prod`: coefficient submodules of a product
  are the supremum of the coefficient submodules of the two factors.
* `TauCeti.Comodule.matrixCoefficientSubalgebra_prod`: the analogous statement for the
  subalgebra generated by coefficients.

## References

This is the standard direct-sum behavior of matrix coefficients of comodules; see Sweedler,
*Hopf Algebras*, Chapter 2. It builds on Tau Ceti's `Comodule.Prod` construction.
-/

open scoped TensorProduct

namespace TauCeti

namespace Comodule

universe u v w x

variable {R : Type u} {C : Type v} {M : Type w} {N : Type x}

section Submodule

variable [CommSemiring R]
variable [AddCommMonoid C] [Module R C] [Coalgebra R C]
variable [AddCommMonoid M] [Module R M] [Comodule R C M]
variable [AddCommMonoid N] [Module R N] [Comodule R C N]

/-- Matrix coefficients of the product comodule split as the sum of the left and right
matrix coefficients. -/
@[simp]
theorem matrixCoefficient_prod (φ : M × N →ₗ[R] R) (x : M × N) :
    letI : Comodule R C (M × N) := Prod (R := R) (C := C) (M := M) (N := N)
    matrixCoefficient (R := R) (C := C) φ x =
      matrixCoefficient (R := R) (C := C) (φ.comp (LinearMap.inl R M N)) x.1 +
        matrixCoefficient (R := R) (C := C) (φ.comp (LinearMap.inr R M N)) x.2 := by
  letI : Comodule R C (M × N) := Prod (R := R) (C := C) (M := M) (N := N)
  simp [matrixCoefficient_def, TensorProduct.map_map]

/-- Matrix coefficients of a left summand, viewed in the product comodule, are the original
left matrix coefficients. -/
@[simp]
theorem matrixCoefficient_prod_inl (φ : M →ₗ[R] R) (m : M) :
    letI : Comodule R C (M × N) := Prod (R := R) (C := C) (M := M) (N := N)
    matrixCoefficient (R := R) (C := C) (φ.comp (LinearMap.fst R M N))
        (LinearMap.inl R M N m) =
      matrixCoefficient (R := R) (C := C) φ m := by
  letI : Comodule R C (M × N) := Prod (R := R) (C := C) (M := M) (N := N)
  rw [matrixCoefficient_prod]
  have hφ :
      (φ.comp (LinearMap.fst R M N)).comp (LinearMap.inl R M N) = φ := by
    ext m
    rfl
  simp [matrixCoefficient_zero, hφ]

/-- Matrix coefficients of a right summand, viewed in the product comodule, are the original
right matrix coefficients. -/
@[simp]
theorem matrixCoefficient_prod_inr (ψ : N →ₗ[R] R) (n : N) :
    letI : Comodule R C (M × N) := Prod (R := R) (C := C) (M := M) (N := N)
    matrixCoefficient (R := R) (C := C) (ψ.comp (LinearMap.snd R M N))
        (LinearMap.inr R M N n) =
      matrixCoefficient (R := R) (C := C) ψ n := by
  letI : Comodule R C (M × N) := Prod (R := R) (C := C) (M := M) (N := N)
  rw [matrixCoefficient_prod]
  have hψ :
      (ψ.comp (LinearMap.snd R M N)).comp (LinearMap.inr R M N) = ψ := by
    ext n
    rfl
  simp [matrixCoefficient_zero, hψ]

/-- The coefficient submodule of the product comodule is the supremum of the coefficient
submodules of the two factors. -/
@[simp]
theorem matrixCoefficientSubmodule_prod :
    letI : Comodule R C (M × N) := Prod (R := R) (C := C) (M := M) (N := N)
    matrixCoefficientSubmodule (R := R) (C := C) (M := M × N) =
      matrixCoefficientSubmodule (R := R) (C := C) (M := M) ⊔
        matrixCoefficientSubmodule (R := R) (C := C) (M := N) := by
  letI : Comodule R C (M × N) := Prod (R := R) (C := C) (M := M) (N := N)
  apply le_antisymm
  · rw [matrixCoefficientSubmodule_le_iff]
    intro φ x
    rw [matrixCoefficient_prod]
    -- The supremum side has two coefficient submodules whose ambient type is the same, so
    -- spell out the target that `mem_sup_left` and `mem_sup_right` should inhabit.
    exact add_mem
      (show matrixCoefficient (R := R) (C := C) (φ.comp (LinearMap.inl R M N)) x.1 ∈
          matrixCoefficientSubmodule (R := R) (C := C) (M := M) ⊔
            matrixCoefficientSubmodule (R := R) (C := C) (M := N) from
        Submodule.mem_sup_left
          (matrixCoefficient_mem_submodule (R := R) (C := C)
            (φ.comp (LinearMap.inl R M N)) x.1))
      (show matrixCoefficient (R := R) (C := C) (φ.comp (LinearMap.inr R M N)) x.2 ∈
          matrixCoefficientSubmodule (R := R) (C := C) (M := M) ⊔
            matrixCoefficientSubmodule (R := R) (C := C) (M := N) from
        Submodule.mem_sup_right
          (matrixCoefficient_mem_submodule (R := R) (C := C)
            (φ.comp (LinearMap.inr R M N)) x.2))
  · apply sup_le
    · rw [matrixCoefficientSubmodule_le_iff]
      intro φ m
      rw [← matrixCoefficient_prod_inl (R := R) (C := C) (M := M) (N := N) φ m]
      exact matrixCoefficient_mem_submodule (R := R) (C := C)
        (φ.comp (LinearMap.fst R M N)) (LinearMap.inl R M N m)
    · rw [matrixCoefficientSubmodule_le_iff]
      intro ψ n
      rw [← matrixCoefficient_prod_inr (R := R) (C := C) (M := M) (N := N) ψ n]
      exact matrixCoefficient_mem_submodule (R := R) (C := C)
        (ψ.comp (LinearMap.snd R M N)) (LinearMap.inr R M N n)

end Submodule

section Algebra

variable [CommSemiring R]
variable [Semiring C] [Algebra R C] [Coalgebra R C]
variable [AddCommMonoid M] [Module R M] [Comodule R C M]
variable [AddCommMonoid N] [Module R N] [Comodule R C N]

/-- The coefficient subalgebra of the product comodule is the supremum of the coefficient
subalgebras of the two factors. -/
@[simp]
theorem matrixCoefficientSubalgebra_prod :
    letI : Comodule R C (M × N) := Prod (R := R) (C := C) (M := M) (N := N)
    matrixCoefficientSubalgebra (R := R) (C := C) (M := M × N) =
      matrixCoefficientSubalgebra (R := R) (C := C) (M := M) ⊔
        matrixCoefficientSubalgebra (R := R) (C := C) (M := N) := by
  letI : Comodule R C (M × N) := Prod (R := R) (C := C) (M := M) (N := N)
  apply le_antisymm
  · rw [matrixCoefficientSubalgebra_le_iff]
    intro φ x
    rw [matrixCoefficient_prod]
    -- As above, the type ascription fixes the intended supremum target for the algebra
    -- membership lemmas.
    exact add_mem
      (show matrixCoefficient (R := R) (C := C) (φ.comp (LinearMap.inl R M N)) x.1 ∈
          matrixCoefficientSubalgebra (R := R) (C := C) (M := M) ⊔
            matrixCoefficientSubalgebra (R := R) (C := C) (M := N) from
        Algebra.mem_sup_left
          (matrixCoefficient_mem_subalgebra (R := R) (C := C)
            (φ.comp (LinearMap.inl R M N)) x.1))
      (show matrixCoefficient (R := R) (C := C) (φ.comp (LinearMap.inr R M N)) x.2 ∈
          matrixCoefficientSubalgebra (R := R) (C := C) (M := M) ⊔
            matrixCoefficientSubalgebra (R := R) (C := C) (M := N) from
        Algebra.mem_sup_right
          (matrixCoefficient_mem_subalgebra (R := R) (C := C)
            (φ.comp (LinearMap.inr R M N)) x.2))
  · apply sup_le
    · rw [matrixCoefficientSubalgebra_le_iff]
      intro φ m
      rw [← matrixCoefficient_prod_inl (R := R) (C := C) (M := M) (N := N) φ m]
      exact matrixCoefficient_mem_subalgebra (R := R) (C := C)
        (φ.comp (LinearMap.fst R M N)) (LinearMap.inl R M N m)
    · rw [matrixCoefficientSubalgebra_le_iff]
      intro ψ n
      rw [← matrixCoefficient_prod_inr (R := R) (C := C) (M := M) (N := N) ψ n]
      exact matrixCoefficient_mem_subalgebra (R := R) (C := C)
        (ψ.comp (LinearMap.snd R M N)) (LinearMap.inr R M N n)

end Algebra

end Comodule

end TauCeti
