/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import TauCeti.Algebra.Coalgebra.Comodule.MatrixCoefficientAdjoin

/-!
# Matrix coefficients of trivial comodules

This file packages the generated coefficient objects for trivial comodules over a bialgebra.
The individual coefficient calculation is already in
`TauCeti.Algebra.Coalgebra.Comodule.MatrixCoefficient`: if `M` has the trivial coaction, then
every coefficient is a scalar multiple of `1`.

Here we record the corresponding span and algebra-generation consequences. For an arbitrary
trivial module, its coefficient submodule is contained in the line spanned by `1`, and its
coefficient subalgebra is contained in the bottom `R`-subalgebra. For the rank-one trivial
comodule `R`, these inclusions are equalities.

This is Layer 1 infrastructure for the reductive-groups roadmap target "Faithfulness done
right": the faithful-representation criterion is stated in terms of the algebra generated by
matrix coefficients, and the tensor-unit/trivial representation should have the expected
coefficient algebra.

## Main declarations

* `TauCeti.Comodule.trivial_matrixCoefficientSubmodule_le_span_singleton_one`.
* `TauCeti.Comodule.trivial_matrixCoefficientSubalgebra_le_bot`.
* `TauCeti.Comodule.trivialRankOne_matrixCoefficientSubmodule_eq_span_singleton_one`.
* `TauCeti.Comodule.trivialRankOne_matrixCoefficientSubalgebra_eq_bot`.

## References

These are the standard coefficient calculations for the trivial comodule, using the existing
Tau Ceti matrix-coefficient API and Mathlib's `Algebra.adjoin`/`Submodule.span` API.
-/

namespace TauCeti

namespace Comodule

universe u v w

variable {R : Type u} {C : Type v}
variable [CommSemiring R] [Semiring C] [Bialgebra R C]

section Arbitrary

variable {M : Type w} [AddCommMonoid M] [Module R M]

attribute [local instance] trivial

/-- A matrix coefficient of a trivial comodule lies in the line spanned by `1`. -/
theorem trivial_matrixCoefficient_mem_span_singleton_one (φ : M →ₗ[R] R) (m : M) :
    matrixCoefficient (R := R) (C := C) φ m ∈ Submodule.span R ({1} : Set C) := by
  rw [matrixCoefficient_trivial]
  exact Submodule.smul_mem _ _ (Submodule.subset_span (Set.mem_singleton 1))

/-- The coefficient submodule of a trivial comodule is contained in the line spanned by `1`. -/
theorem trivial_matrixCoefficientSubmodule_le_span_singleton_one :
    matrixCoefficientSubmodule (R := R) (C := C) (M := M) ≤
      Submodule.span R ({1} : Set C) :=
  matrixCoefficientSubmodule_le (R := R) (C := C) (M := M)
    trivial_matrixCoefficient_mem_span_singleton_one

/-- A matrix coefficient of a trivial comodule lies in the bottom `R`-subalgebra. -/
theorem trivial_matrixCoefficient_mem_bot (φ : M →ₗ[R] R) (m : M) :
    matrixCoefficient (R := R) (C := C) φ m ∈ (⊥ : Subalgebra R C) := by
  rw [matrixCoefficient_trivial]
  exact (⊥ : Subalgebra R C).smul_mem (one_mem _) (φ m)

/-- The coefficient algebra of a trivial comodule is contained in the bottom subalgebra. -/
theorem trivial_matrixCoefficientSubalgebra_le_bot :
    matrixCoefficientSubalgebra (R := R) (C := C) (M := M) ≤ ⊥ :=
  matrixCoefficientSubalgebra_le (R := R) (C := C) (M := M)
    trivial_matrixCoefficient_mem_bot

end Arbitrary

section RankOne

attribute [local instance] trivial

/-- The element `1` is a matrix coefficient of the rank-one trivial comodule. -/
theorem one_mem_trivialRankOne_matrixCoefficientSet :
    (1 : C) ∈ matrixCoefficientSet (R := R) (C := C) (M := R) := by
  rw [mem_matrixCoefficientSet_iff]
  exact ⟨LinearMap.id, 1, by simp⟩

/-- The coefficient set of the rank-one trivial comodule spans exactly the line generated by
`1`. -/
@[simp]
theorem trivialRankOne_matrixCoefficientSubmodule_eq_span_singleton_one :
    matrixCoefficientSubmodule (R := R) (C := C) (M := R) =
      Submodule.span R ({1} : Set C) := by
  apply le_antisymm
  · exact trivial_matrixCoefficientSubmodule_le_span_singleton_one (R := R) (C := C) (M := R)
  · rw [Submodule.span_le]
    intro c hc
    rw [Set.mem_singleton_iff.mp hc]
    exact Submodule.subset_span one_mem_trivialRankOne_matrixCoefficientSet

/-- The coefficient algebra of the rank-one trivial comodule is the bottom `R`-subalgebra. -/
@[simp]
theorem trivialRankOne_matrixCoefficientSubalgebra_eq_bot :
    matrixCoefficientSubalgebra (R := R) (C := C) (M := R) = ⊥ := by
  apply le_antisymm
  · exact trivial_matrixCoefficientSubalgebra_le_bot (R := R) (C := C) (M := R)
  · exact bot_le

end RankOne

end Comodule

end TauCeti
