/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib.LinearAlgebra.Finsupp.LSum
import Mathlib.Data.Fintype.Perm
import TauCeti.KnotTheory.Grid.BlockedRectangle

/-!
# The fully blocked grid chain module

This file packages the first algebraic object in the grid-combinatorial lane: the free
`ZMod 2`-module on grid states, together with the linear map whose matrix coefficient from
`x` to `y` is the parity of fully blocked empty rectangles from `x` to `y`.

The square-zero theorem is deliberately not asserted here. This module only supplies the
concrete finite free module and differential map to which the later rectangle-pairing proof
will apply.

## Main definitions

* `TauCeti.GridChain`: the free `ZMod 2`-module generated by grid states.
* `TauCeti.GridChain.basis`: the basis vector attached to one grid state.
* `TauCeti.GridDiagram.fullyBlockedDifferentialOnGenerator`: the row of the fully blocked
  differential on one generator.
* `TauCeti.GridDiagram.fullyBlockedDifferential`: the corresponding `ZMod 2`-linear map.

## References

This supplies a prerequisite for `TauCetiRoadmap/HeegaardFloer/README.md`, Lane G.3,
"The complexes and `∂² = 0`. Fully blocked `GC̃` over 𝔽₂ (rectangles avoiding all
markings)". The coefficient formula follows Ozsváth--Stipsicz--Szabó, *Grid Homology for
Knots and Links*, Chapter 3.
-/

namespace TauCeti

namespace GridState

variable {n : ℕ}

/-- Grid states are equivalent to permutations of the columns. -/
def equivPerm : GridState n ≃ Equiv.Perm (Fin n) where
  toFun x := x.toPerm
  invFun σ := ⟨σ⟩
  left_inv x := by cases x; rfl
  right_inv σ := rfl

/-- There are finitely many grid states of a fixed grid size. -/
noncomputable instance : Fintype (GridState n) :=
  Fintype.ofEquiv (Equiv.Perm (Fin n)) equivPerm.symm

end GridState

/-- The free `ZMod 2`-module generated by grid states of size `n`. -/
abbrev GridChain (n : ℕ) :=
  GridState n →₀ ZMod 2

namespace GridChain

variable {n : ℕ}

/-- The basis vector corresponding to a grid state. -/
noncomputable def basis (x : GridState n) : GridChain n :=
  Finsupp.single x 1

/-- The coefficient of a basis vector in itself is one. -/
@[simp]
theorem basis_apply_self (x : GridState n) : basis x x = 1 := by
  classical
  simp [basis]

/-- The coefficient of another basis vector is zero. -/
@[simp]
theorem basis_apply_ne {x y : GridState n} (h : y ≠ x) : basis x y = 0 := by
  classical
  simp [basis, h]

end GridChain

namespace GridDiagram

variable {n : ℕ} (G : GridDiagram n)

/-- The value of the fully blocked differential on a single grid-state generator.

Its `y`-coefficient is the parity of fully blocked empty rectangles from `x` to `y`. -/
noncomputable def fullyBlockedDifferentialOnGenerator (x : GridState n) : GridChain n :=
  Finset.univ.sum fun y : GridState n =>
    Finsupp.single y (G.fullyBlockedRectangleCount x y)

/-- The generator row of the fully blocked differential is the finite sum of rectangle-count
coefficients. -/
theorem fullyBlockedDifferentialOnGenerator_def (x : GridState n) :
    G.fullyBlockedDifferentialOnGenerator x =
      Finset.univ.sum fun y : GridState n =>
        Finsupp.single y (G.fullyBlockedRectangleCount x y) :=
  rfl

/-- The `y`-coefficient of the fully blocked differential on the generator `x`. -/
@[simp]
theorem fullyBlockedDifferentialOnGenerator_apply (x y : GridState n) :
    G.fullyBlockedDifferentialOnGenerator x y = G.fullyBlockedRectangleCount x y := by
  classical
  rw [fullyBlockedDifferentialOnGenerator]
  rw [Finsupp.finsetSum_apply]
  rw [Finset.sum_eq_single y]
  · simp
  · intro z _ hz
    simp [hz.symm]
  · intro hy
    exact (hy (Finset.mem_univ y)).elim

/-- The fully blocked grid differential as a `ZMod 2`-linear map on chains. -/
noncomputable def fullyBlockedDifferential : GridChain n →ₗ[ZMod 2] GridChain n :=
  Finsupp.lsum (ZMod 2) fun x : GridState n =>
    (LinearMap.id : ZMod 2 →ₗ[ZMod 2] ZMod 2).smulRight
      (G.fullyBlockedDifferentialOnGenerator x)

/-- The fully blocked differential sends a basis vector to the corresponding rectangle-count
row. -/
@[simp]
theorem fullyBlockedDifferential_basis (x : GridState n) :
    G.fullyBlockedDifferential (GridChain.basis x) =
      G.fullyBlockedDifferentialOnGenerator x := by
  classical
  rw [GridChain.basis, fullyBlockedDifferential]
  rw [Finsupp.lsum_single]
  simp

/-- The matrix coefficient of the fully blocked differential on a basis vector is the fully
blocked rectangle count. -/
@[simp]
theorem fullyBlockedDifferential_basis_apply (x y : GridState n) :
    G.fullyBlockedDifferential (GridChain.basis x) y =
      G.fullyBlockedRectangleCount x y := by
  simp

/-- There is no self-term in the fully blocked differential of a generator. -/
@[simp]
theorem fullyBlockedDifferentialOnGenerator_apply_self (x : GridState n) :
    G.fullyBlockedDifferentialOnGenerator x x = 0 := by
  simp

/-- The self-coefficient of the fully blocked differential on a basis vector is zero. -/
@[simp]
theorem fullyBlockedDifferential_basis_apply_self (x : GridState n) :
    G.fullyBlockedDifferential (GridChain.basis x) x = 0 := by
  simp

/-- The fully blocked differential is the finite sum of its generator rows over the support
of a chain. -/
theorem fullyBlockedDifferential_apply (c : GridChain n) :
    G.fullyBlockedDifferential c =
      c.sum fun x a => a • G.fullyBlockedDifferentialOnGenerator x := by
  rw [fullyBlockedDifferential]
  rfl

/-- The coefficient formula for the fully blocked differential on an arbitrary chain. -/
theorem fullyBlockedDifferential_apply_apply (c : GridChain n) (y : GridState n) :
    G.fullyBlockedDifferential c y =
      c.sum fun x a => a * G.fullyBlockedRectangleCount x y := by
  classical
  rw [fullyBlockedDifferential_apply]
  simp [Finsupp.sum_apply]

end GridDiagram

end TauCeti
