/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import TauCeti.NumberTheory.Multiquadratic.SquareClass

/-!
# The degree of a multiquadratic field

For square roots `root j` of radicands `d j` over a field `K` (characteristic not two), the
multiquadratic field `K(root₀, …, rootₙ₋₁)` has degree `2ⁿ` over `K` when the radicands are
**square-class independent**: no nonempty subset product `∏_{j ∈ S} d j` is a square. Each
tower step adjoins a root of the degree-two polynomial `X² - d j`, doubling the degree, and
square-class descent shows the new root is genuinely outside the previous stage.

## Main results

* `TauCeti.Multiquadratic.finrank_sqrtTower`: `[K(root₀,…,rootₙ₋₁) : K] = 2ⁿ`.
* `TauCeti.Multiquadratic.finrank_adjoin_range`: the same over a finite index type,
  `[K(rootᵢ : i) : K] = 2^|ι|` — the multiquadratic degree target.

## Provenance

The tower-degree induction is migrated and generalised from the declaration
`sqrtTower_finrank` in `ErdosUnitDistance/MultiquadraticField.lean` in
[kim-em/erdos-unit-distance](https://github.com/kim-em/erdos-unit-distance), the formalization
of L. Alpöge's disproof of the uniform-constant Erdős unit-distance conjecture.
-/

open TauCeti.IntermediateField

namespace TauCeti.Multiquadratic

variable {K L : Type*} [Field K] [Field L] [Algebra K L]

/-- **Degree of a multiquadratic tower.** If no nonempty subset product of the radicands `d j`
(`j < n`) is a square in `K`, then `[K(root₀, …, rootₙ₋₁) : K] = 2ⁿ`. -/
theorem finrank_sqrtTower {d : ℕ → K} {root : ℕ → L}
    (hroot : ∀ j, root j ^ 2 = algebraMap K L (d j)) [NeZero (2 : K)] :
    ∀ n, (∀ S : Finset ℕ, S.Nonempty → ↑S ⊆ Set.Iio n → ¬ IsSquare (∏ j ∈ S, d j)) →
      Module.finrank K (sqrtTower (K := K) root n) = 2 ^ n := by
  intro n
  induction n with
  | zero => intro _; rw [sqrtTower_zero, pow_zero]; exact IntermediateField.finrank_bot
  | succ n ih =>
      intro hindep
      rw [sqrtTower_succ]
      have hx2 : root n ^ 2 ∈ sqrtTower root n := sqrtTower_sq_mem root d hroot
      have hxK : root n ∉ sqrtTower (K := K) root n := by
        intro hmem
        obtain ⟨T, s, hT, heq⟩ :=
          squareClass_of_sq_mem d root hroot n (d n) (root n) (hroot n) hmem
        have hnT : n ∉ T := fun h =>
          absurd (Set.mem_Iio.mp (hT (Finset.mem_coe.mpr h))) (lt_irrefl n)
        refine hindep (insert n T) (Finset.insert_nonempty n T) ?_ ?_
        · intro k hk
          rw [Finset.coe_insert, Set.mem_insert_iff] at hk
          rcases hk with rfl | hk
          · exact Set.mem_Iio.mpr (Nat.lt_succ_self _)
          · exact Set.Iio_subset_Iio (Nat.le_succ n) (hT hk)
        · rw [Finset.prod_insert hnT, heq]
          exact ⟨s * ∏ j ∈ T, d j, by ring⟩
      rw [finrank_sup_adjoin_simple_eq_mul_two _ hx2 hxK,
        ih (fun S hS hsub => hindep S hS (hsub.trans (Set.Iio_subset_Iio (Nat.le_succ n)))),
        pow_succ]

/-- **Degree of a multiquadratic field over a finite index.** If no nonempty subset product of
the radicands `d i` is a square in `K`, then `[K(rootᵢ : i) : K] = 2^|ι|`. -/
theorem finrank_adjoin_range {ι : Type*} [Finite ι] {d : ι → K} {root : ι → L}
    (hroot : ∀ i, root i ^ 2 = algebraMap K L (d i)) [NeZero (2 : K)]
    (hindep : ∀ S : Finset ι, S.Nonempty → ¬ IsSquare (∏ i ∈ S, d i)) :
    Module.finrank K (IntermediateField.adjoin K (Set.range root)) = 2 ^ Nat.card ι := by
  classical
  letI := Fintype.ofFinite ι
  let e : ι ≃ Fin (Fintype.card ι) := Fintype.equivFin ι
  -- Pad the data to `ℕ`, with `1` (a harmless square) beyond the index range.
  let toι : ∀ {j : ℕ}, j < Fintype.card ι → ι := fun {j} h => e.symm ⟨j, h⟩
  let dN : ℕ → K := fun j => if h : j < Fintype.card ι then d (toι h) else 1
  let rootN : ℕ → L := fun j => if h : j < Fintype.card ι then root (toι h) else 1
  have hrootN : ∀ j, rootN j ^ 2 = algebraMap K L (dN j) := by
    intro j
    by_cases h : j < Fintype.card ι <;> simp [rootN, dN, h, hroot]
  -- The tower of the first `|ι|` padded roots is the field generated by all the `root i`.
  have hfield : sqrtTower (K := K) rootN (Fintype.card ι)
      = IntermediateField.adjoin K (Set.range root) := by
    rw [sqrtTower_eq_adjoin_fin_range]
    congr 1
    ext z
    constructor
    · rintro ⟨i, rfl⟩
      exact ⟨e.symm i, by simp [rootN, toι, i.2]⟩
    · rintro ⟨i, rfl⟩
      exact ⟨e i, by simp [rootN, toι, (e i).2]⟩
  rw [← hfield]
  rw [Nat.card_eq_fintype_card]
  refine finrank_sqrtTower hrootN (Fintype.card ι) (fun S hSne hSsub => ?_)
  -- Reindex the subset product over `ℕ` to one over `ι`, then apply `hindep`.
  have hmem : ∀ j ∈ S, j < Fintype.card ι := fun j hj => Set.mem_Iio.mp (hSsub hj)
  set S' : Finset ι := S.attach.image (fun j => toι (hmem j.1 j.2)) with hS'
  have hS'ne : S'.Nonempty := by
    obtain ⟨j, hj⟩ := hSne
    exact ⟨toι (hmem j hj), Finset.mem_image.mpr ⟨⟨j, hj⟩, Finset.mem_attach _ _, rfl⟩⟩
  have hprod : ∏ j ∈ S, dN j = ∏ i ∈ S', d i := by
    rw [hS', Finset.prod_image]
    · rw [← Finset.prod_attach S (fun j => dN j)]
      refine Finset.prod_congr rfl fun j _ => ?_
      simp [dN, hmem j.1 j.2]
    · rintro ⟨a, ha⟩ _ ⟨b, hb⟩ _ hab
      simpa [toι, e.symm.injective.eq_iff, Fin.mk.injEq] using hab
  rw [hprod]
  exact hindep S' hS'ne

end TauCeti.Multiquadratic
