/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.NumberTheory.Multiquadratic.GaloisGroup
public import TauCeti.NumberTheory.Multiquadratic.PrimeDiscriminantIndependence
public import Mathlib.Data.Complex.Basic
public import Mathlib.Analysis.Real.Sqrt

/-!
# Galois groups from prime-discriminant radicands

The genus-field layer of the multiquadratic roadmap uses prime discriminants `D` but adjoins
square roots of the associated squarefree radicands `primeDiscriminantRadicand D`: `-1`, `2`,
`-2`, or an odd prime discriminant itself. The field-generic Galois-group theorem
`TauCeti.Multiquadratic.galoisGroupEquiv` already identifies the Galois group of a
square-class-independent multiquadratic field with `(ℤ/2)ⁿ`. This file packages the
prime-discriminant instance, using
`TauCeti.Multiquadratic.not_isSquare_prod_primeDiscriminantRadicands` for the independence
hypothesis.

## Main results

* `TauCeti.Multiquadratic.galoisGroupEquivPrimeDiscriminantRadicands`: for an injective family
  of prime discriminants not containing all three even prime discriminants, the Galois group of
  the field generated by roots of their radicands is `Multiplicative (ι → ZMod 2)`.
* `TauCeti.Multiquadratic.card_aut_adjoin_roots_primeDiscriminantRadicands`: the corresponding
  cardinality statement.
* `TauCeti.Multiquadratic.card_aut_adjoin_I_sqrt_five`: the genus-field-generator example
  `|Gal(ℚ(i, √5)/ℚ)| = 4`, attached to the prime discriminants `-4` and `5`.
-/

public section

open IntermediateField

namespace TauCeti.Multiquadratic

variable {ι : Type*}

section PrimeDiscriminantFamily

variable [Finite ι] {L : Type*} [Field L] [Algebra ℚ L] (D : ι → ℤ)
  (hD : ∀ i, IsPrimeDiscriminant (D i)) (hinj : Function.Injective D)
  (heven : ¬ ((∃ i, D i = -4) ∧ (∃ i, D i = 8) ∧ (∃ i, D i = -8)))
  (root : ι → L)
  (hroot : ∀ i, root i ^ 2 =
    algebraMap ℚ L ((primeDiscriminantRadicand (D i) : ℤ) : ℚ))

/-- **The Galois group from prime-discriminant radicands is `(ℤ/2)ⁿ`.** For an injective
family of prime discriminants `D : ι → ℤ` which does not contain all three even prime
discriminants `-4`, `8`, and `-8`, and chosen roots of their squarefree radicands, the Galois
group of the generated multiquadratic field is `Multiplicative (ι → ZMod 2)`. This is the
prime-discriminant instance of the field-generic `galoisGroupEquiv`. -/
noncomputable def galoisGroupEquivPrimeDiscriminantRadicands :
    (adjoin ℚ (Set.range root) ≃ₐ[ℚ] adjoin ℚ (Set.range root)) ≃*
      Multiplicative (ι → ZMod 2) :=
  galoisGroupEquiv hroot
    (not_isSquare_prod_primeDiscriminantRadicands D hD hinj heven)

/-- The prime-discriminant Galois equivalence sends an automorphism to its sign pattern on the
chosen radicand roots. -/
@[simp] theorem galoisGroupEquivPrimeDiscriminantRadicands_apply
    (σ : adjoin ℚ (Set.range root) ≃ₐ[ℚ] adjoin ℚ (Set.range root)) :
    galoisGroupEquivPrimeDiscriminantRadicands D hD hinj heven root hroot σ =
      Multiplicative.ofAdd (signPattern root σ) :=
  galoisGroupEquiv_apply hroot
    (not_isSquare_prod_primeDiscriminantRadicands D hD hinj heven) σ

/-- The inverse prime-discriminant Galois equivalence realizes a sign pattern by sending each
chosen generator to `(-1)^(ε i)` times that generator. -/
@[simp] theorem galoisGroupEquivPrimeDiscriminantRadicands_symm_apply_gen
    (ε : ι → ZMod 2) (i : ι) :
    ((galoisGroupEquivPrimeDiscriminantRadicands D hD hinj heven root hroot).symm
        (Multiplicative.ofAdd ε)) (gen root i)
      = (-1) ^ (ε i).val * gen root i :=
  galoisGroupEquiv_symm_apply_gen hroot
    (not_isSquare_prod_primeDiscriminantRadicands D hD hinj heven) ε i

include hD hinj heven hroot in
/-- **Cardinality of the Galois group from prime-discriminant radicands.** Under the same
prime-discriminant hypotheses, `|Gal(ℚ(rootᵢ : i)/ℚ)| = 2^|ι|`. -/
theorem card_aut_adjoin_roots_primeDiscriminantRadicands :
    Nat.card (adjoin ℚ (Set.range root) ≃ₐ[ℚ] adjoin ℚ (Set.range root)) =
      2 ^ Nat.card ι :=
  card_aut_adjoin_range hroot
    (not_isSquare_prod_primeDiscriminantRadicands D hD hinj heven)

end PrimeDiscriminantFamily

/-- The complex square root data for the two prime discriminants `-4` and `5`: the associated
radicands are `-1` and `5`, with roots `i` and `√5`. -/
private theorem root_neg_four_five_sq (i : Fin 2) :
    (fun i : Fin 2 => ![Complex.I, ((Real.sqrt 5 : ℝ) : ℂ)] i) i ^ 2 =
      algebraMap ℚ ℂ
        (((primeDiscriminantRadicand (![(-4 : ℤ), 5] i) : ℤ) : ℚ)) := by
  fin_cases i
  · simp [Complex.I_sq]
  · have h : (((Real.sqrt 5 : ℝ) : ℂ) ^ 2) = (5 : ℂ) := by
      rw [← Complex.ofReal_pow, Real.sq_sqrt (by norm_num : (0 : ℝ) ≤ 5)]
      norm_num
    simpa [primeDiscriminantRadicand] using h

/-- **Worked example: `|Gal(ℚ(i, √5)/ℚ)| = 4`.** This is the Galois group of the
multiquadratic field generated by the radicands attached to the prime discriminants `-4` and
`5`, the genus-field generators for `ℚ(√-5)`. -/
theorem card_aut_adjoin_I_sqrt_five :
    Nat.card
      ((adjoin ℚ ({Complex.I, ((Real.sqrt 5 : ℝ) : ℂ)} : Set ℂ) :
          IntermediateField ℚ ℂ)
          ≃ₐ[ℚ]
        (adjoin ℚ ({Complex.I, ((Real.sqrt 5 : ℝ) : ℂ)} : Set ℂ) :
          IntermediateField ℚ ℂ))
      = 4 := by
  have hD : ∀ i : Fin 2, IsPrimeDiscriminant (![(-4 : ℤ), 5] i) := by
    intro i
    fin_cases i
    · simp
    · have h5 : IsPrimeDiscriminant (5 : ℤ) := by
        simpa [oddPrimeDiscriminant_of_mod_four_eq_one (by norm_num : 5 % 4 = 1)]
          using isPrimeDiscriminant_oddPrimeDiscriminant (p := 5) (by decide) (by decide)
      simpa using h5
  have hinj : Function.Injective (![(-4 : ℤ), 5] : Fin 2 → ℤ) := by
    decide
  have heven :
      ¬ ((∃ i : Fin 2, (![(-4 : ℤ), 5] i) = -4) ∧
        (∃ i : Fin 2, (![(-4 : ℤ), 5] i) = 8) ∧
          (∃ i : Fin 2, (![(-4 : ℤ), 5] i) = -8)) := by
    simp
  have h := card_aut_adjoin_roots_primeDiscriminantRadicands (![(-4 : ℤ), 5])
    hD hinj heven (fun i : Fin 2 => ![Complex.I, ((Real.sqrt 5 : ℝ) : ℂ)] i)
    root_neg_four_five_sq
  have hset : (Set.range fun i : Fin 2 => ![Complex.I, ((Real.sqrt 5 : ℝ) : ℂ)] i)
      = {Complex.I, ((Real.sqrt 5 : ℝ) : ℂ)} := by
    ext x
    simp only [Set.mem_range, Set.mem_insert_iff, Set.mem_singleton_iff]
    constructor
    · intro hx
      rcases hx with ⟨i, rfl⟩
      fin_cases i <;> simp
    · intro hx
      rcases hx with hx | hx
      · exact ⟨0, by simp [hx]⟩
      · exact ⟨1, by simp [hx]⟩
  rw [hset] at h
  exact h.trans (by norm_num [Nat.card_fin])

end TauCeti.Multiquadratic
