/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.NumberTheory.Multiquadratic.PrimeRadicands
public import TauCeti.NumberTheory.Multiquadratic.SubfieldLattice

/-!
# Prime-radicand subfield lattices

This file specializes the field-generic multiquadratic subfield/subspace dictionary from
`TauCeti.NumberTheory.Multiquadratic.SubfieldLattice` to fields
`ℚ(√p₁, …, √pₙ)` generated by square roots of a finite family of distinct primes. The prime-specific
square-class independence input comes from `TauCeti.NumberTheory.Multiquadratic.PrimeRadicands`.

## Main results

* `TauCeti.Multiquadratic.intermediateFieldEquivSubmoduleSqrtPrimes`: for a finite family of
  distinct primes `p : ι → ℕ`, the order-reversing bijection between intermediate fields of
  `ℚ(√p₁, …, √pₙ)` and `𝔽₂`-subspaces of `ι → ℤ/2`.
* `TauCeti.Multiquadratic.card_intermediateField_adjoin_sqrt_primes`: the corresponding
  cardinality statement.
-/

public section

open IntermediateField

namespace TauCeti.Multiquadratic

variable {ι : Type*}

section PrimeFamily

variable [Finite ι] (p : ι → ℕ) (hp : ∀ i, (p i).Prime) (hinj : Function.Injective p)

omit [Finite ι] in
/-- The square roots `√(p i)` of a prime family satisfy the radicand equation `√(p i)² = p i`. -/
private theorem sqrtPrime_sq (i : ι) : Real.sqrt (p i) ^ 2 = algebraMap ℚ ℝ (p i : ℚ) :=
  sq_sqrt_natCast (p i)

include hp hinj

/-- **The subfield lattice of `ℚ(√p₁, …, √pₙ)`.** For a finite family of distinct primes
`p : ι → ℕ`, the intermediate fields of `ℚ(√p₁, …, √pₙ)/ℚ` correspond, order-reversingly, to the
`𝔽₂`-subspaces of `ι → ℤ/2`. This is the prime-radicand specialization of
`intermediateFieldEquivSubmodule`, a genus-theory input. -/
noncomputable def intermediateFieldEquivSubmoduleSqrtPrimes :
    IntermediateField ℚ (adjoin ℚ (Set.range fun i => (Real.sqrt (p i) : ℝ))) ≃o
      (Submodule (ZMod 2) (ι → ZMod 2))ᵒᵈ :=
  intermediateFieldEquivSubmodule (sqrtPrime_sq p)
    (not_isSquare_prod_primes_of_injective p hp hinj)

/-- A sign vector belongs to the subspace attached to an intermediate field of
`ℚ(√p₁, …, √pₙ)` exactly when it is the sign pattern of an automorphism fixing that field. -/
@[simp] theorem mem_intermediateFieldEquivSubmoduleSqrtPrimes_apply_ofDual_iff
    (F : IntermediateField ℚ (adjoin ℚ (Set.range fun i => (Real.sqrt (p i) : ℝ))))
    (v : ι → ZMod 2) :
    v ∈ (intermediateFieldEquivSubmoduleSqrtPrimes p hp hinj F).ofDual ↔
      ∃ σ ∈ F.fixingSubgroup, signPattern (fun i => (Real.sqrt (p i) : ℝ)) σ = v :=
  mem_intermediateFieldEquivSubmodule_apply_ofDual_iff (sqrtPrime_sq p)
    (not_isSquare_prod_primes_of_injective p hp hinj) F v

/-- The intermediate field attached to a subspace in the prime-radicand dictionary is the fixed
field of the automorphisms whose sign patterns lie in that subspace. -/
@[simp] theorem mem_intermediateFieldEquivSubmoduleSqrtPrimes_symm_apply_iff
    (U : Submodule (ZMod 2) (ι → ZMod 2))
    (x : adjoin ℚ (Set.range fun i => (Real.sqrt (p i) : ℝ))) :
    x ∈ (intermediateFieldEquivSubmoduleSqrtPrimes p hp hinj).symm (OrderDual.toDual U) ↔
      ∀ σ, signPattern (fun i => (Real.sqrt (p i) : ℝ)) σ ∈ U → σ x = x :=
  mem_intermediateFieldEquivSubmodule_symm_apply_iff (sqrtPrime_sq p)
    (not_isSquare_prod_primes_of_injective p hp hinj) U x

/-- **The number of subfields of `ℚ(√p₁, …, √pₙ)`.** For a finite family of distinct primes, the
intermediate fields of `ℚ(√p₁, …, √pₙ)/ℚ` are in bijection with the `𝔽₂`-subspaces of `ι → ℤ/2`. -/
theorem card_intermediateField_adjoin_sqrt_primes :
    Nat.card (IntermediateField ℚ (adjoin ℚ (Set.range fun i => (Real.sqrt (p i) : ℝ))))
      = Nat.card (Submodule (ZMod 2) (ι → ZMod 2)) :=
  card_intermediateField_adjoin_range (sqrtPrime_sq p)
    (not_isSquare_prod_primes_of_injective p hp hinj)

end PrimeFamily

end TauCeti.Multiquadratic
