/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.NumberTheory.Multiquadratic.PrimeDiscriminantIndependence
public import TauCeti.NumberTheory.Multiquadratic.SubfieldDegree

/-!
# Prime-discriminant subfield lattices

The genus-field layer uses prime discriminants `D`, but the multiquadratic field is generated by
roots of the associated squarefree radicands `primeDiscriminantRadicand D`. This file specializes
the field-generic multiquadratic subfield/subspace dictionary and its degree API to those
prime-discriminant radicands.

The hypotheses are the same as the prime-discriminant degree and Galois-group packages: an
injective family of prime discriminants which does not contain all three even prime discriminants
`-4`, `8`, and `-8`. The excluded triple is exactly the dependence among the even radicands
`-1`, `2`, and `-2`.

## Main results

* `TauCeti.Multiquadratic.intermediateFieldEquivSubmodulePrimeDiscriminantRadicands`: the
  order-reversing bijection between intermediate fields of the prime-discriminant
  multiquadratic field and `𝔽₂`-subspaces of `ι → ℤ/2`.
* `TauCeti.Multiquadratic.card_intermediateField_adjoin_roots_primeDiscriminantRadicands`: the
  corresponding count of intermediate fields.
* `TauCeti.Multiquadratic.finrank_intermediateField_primeDiscriminantRadicands_eq_two_pow` and
  `TauCeti.Multiquadratic.finrank_intermediateField_primeDiscriminantRadicands_eq_two_iff`: the
  degree and quadratic-subfield readings in prime-discriminant form.
-/

public section

open IntermediateField Module

namespace TauCeti.Multiquadratic

variable {ι : Type*}

section PrimeDiscriminantFamily

variable [Finite ι] {L : Type*} [Field L] [Algebra ℚ L] (D : ι → ℤ)
  (hD : ∀ i, IsPrimeDiscriminant (D i)) (hinj : Function.Injective D)
  (heven : ¬ ((∃ i, D i = -4) ∧ (∃ i, D i = 8) ∧ (∃ i, D i = -8)))
  (root : ι → L)
  (hroot : ∀ i, root i ^ 2 =
    algebraMap ℚ L ((primeDiscriminantRadicand (D i) : ℤ) : ℚ))

/-- **The subfield lattice from prime-discriminant radicands.** For an injective family of prime
discriminants not containing the dependent even triple `-4`, `8`, and `-8`, the intermediate
fields of the multiquadratic extension generated by roots of `primeDiscriminantRadicand (D i)`
correspond, order-reversingly, to the `𝔽₂`-subspaces of `ι → ℤ/2`. -/
noncomputable def intermediateFieldEquivSubmodulePrimeDiscriminantRadicands :
    IntermediateField ℚ (adjoin ℚ (Set.range root)) ≃o
      (Submodule (ZMod 2) (ι → ZMod 2))ᵒᵈ :=
  intermediateFieldEquivSubmodule hroot
    (not_isSquare_prod_primeDiscriminantRadicands D hD hinj heven)

/-- A sign vector belongs to the subspace attached to an intermediate field of a
prime-discriminant multiquadratic field exactly when it is the sign pattern of an automorphism
fixing that field. -/
@[simp] theorem mem_intermediateFieldEquivSubmodulePrimeDiscriminantRadicands_apply_ofDual_iff
    (F : IntermediateField ℚ (adjoin ℚ (Set.range root))) (v : ι → ZMod 2) :
    v ∈ (intermediateFieldEquivSubmodulePrimeDiscriminantRadicands
        D hD hinj heven root hroot F).ofDual ↔
      ∃ σ ∈ F.fixingSubgroup, signPattern root σ = v :=
  mem_intermediateFieldEquivSubmodule_apply_ofDual_iff hroot
    (not_isSquare_prod_primeDiscriminantRadicands D hD hinj heven) F v

/-- The intermediate field attached to a subspace in the prime-discriminant dictionary is the
fixed field of the automorphisms whose sign patterns lie in that subspace. -/
@[simp] theorem mem_intermediateFieldEquivSubmodulePrimeDiscriminantRadicands_symm_apply_iff
    (U : Submodule (ZMod 2) (ι → ZMod 2)) (x : adjoin ℚ (Set.range root)) :
    x ∈ (intermediateFieldEquivSubmodulePrimeDiscriminantRadicands
        D hD hinj heven root hroot).symm (OrderDual.toDual U) ↔
      ∀ σ, signPattern root σ ∈ U → σ x = x :=
  mem_intermediateFieldEquivSubmodule_symm_apply_iff hroot
    (not_isSquare_prod_primeDiscriminantRadicands D hD hinj heven) U x

include hD hinj heven hroot

/-- **The number of subfields from prime-discriminant radicands.** Under the prime-discriminant
independence hypotheses, the intermediate fields are counted by the `𝔽₂`-subspaces of
`ι → ℤ/2`. -/
theorem card_intermediateField_adjoin_roots_primeDiscriminantRadicands :
    Nat.card (IntermediateField ℚ (adjoin ℚ (Set.range root)))
      = Nat.card (Submodule (ZMod 2) (ι → ZMod 2)) :=
  card_intermediateField_adjoin_range hroot
    (not_isSquare_prod_primeDiscriminantRadicands D hD hinj heven)

/-- **Degree/subspace-size relation in prime-discriminant form.** For an intermediate field `F`
of a prime-discriminant multiquadratic field, `[F : ℚ]` times the size of its attached subspace is
`2 ^ |ι|`. -/
theorem finrank_mul_card_intermediateFieldEquivSubmodulePrimeDiscriminantRadicands
    (F : IntermediateField ℚ (adjoin ℚ (Set.range root))) :
    Module.finrank ℚ F
        * Nat.card (intermediateFieldEquivSubmodulePrimeDiscriminantRadicands
          D hD hinj heven root hroot F).ofDual
      = 2 ^ Nat.card ι :=
  finrank_mul_card_intermediateFieldEquivSubmodule hroot
    (not_isSquare_prod_primeDiscriminantRadicands D hD hinj heven) F

/-- **Degree of a prime-discriminant intermediate field.** The degree of an intermediate field
is `2` to the codimension of its attached subspace. -/
theorem finrank_intermediateField_primeDiscriminantRadicands_eq_two_pow
    (F : IntermediateField ℚ (adjoin ℚ (Set.range root))) :
    Module.finrank ℚ F =
      2 ^ (Nat.card ι - Module.finrank (ZMod 2)
        (intermediateFieldEquivSubmodulePrimeDiscriminantRadicands
          D hD hinj heven root hroot F).ofDual) :=
  finrank_intermediateField_eq_two_pow hroot
    (not_isSquare_prod_primeDiscriminantRadicands D hD hinj heven) F

/-- **Quadratic subfields in prime-discriminant form.** An intermediate field has degree `2`
exactly when its attached subspace is a hyperplane. -/
theorem finrank_intermediateField_primeDiscriminantRadicands_eq_two_iff
    (F : IntermediateField ℚ (adjoin ℚ (Set.range root))) :
    Module.finrank ℚ F = 2 ↔
      Module.finrank (ZMod 2)
          (intermediateFieldEquivSubmodulePrimeDiscriminantRadicands
            D hD hinj heven root hroot F).ofDual + 1 = Nat.card ι :=
  finrank_intermediateField_eq_two_iff hroot
    (not_isSquare_prod_primeDiscriminantRadicands D hD hinj heven) F

end PrimeDiscriminantFamily

end TauCeti.Multiquadratic
