/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.NumberTheory.Multiquadratic.PrimeSubfieldLattice
public import TauCeti.NumberTheory.Multiquadratic.SubfieldDegree

/-!
# Prime-radicand multiquadratic subfield degrees

The file `TauCeti.NumberTheory.Multiquadratic.PrimeSubfieldLattice` specializes the
multiquadratic subfield/subspace dictionary to fields `ℚ(√p₁, …, √pₙ)` generated by square
roots of a finite family of distinct primes. The generic degree API in
`TauCeti.NumberTheory.Multiquadratic.SubfieldDegree` applies to that dictionary after supplying
the square-root equation and the prime-family square-class-independence proof.

## Main results

* `TauCeti.Multiquadratic.intermediateFieldEquivSubmoduleSqrtPrimes_apply_ofDual_eq`:
  the `ofDual` subspace from the public prime-radicand dictionary agrees with the generic
  dictionary specialized to `sq_sqrt_natCast` and
  `not_isSquare_prod_primes_of_injective`.
* `TauCeti.Multiquadratic.finrank_mul_card_intermediateFieldEquivSubmoduleSqrtPrimes`:
  `[F : ℚ]` times the size of its attached prime-radicand subspace is `2 ^ |ι|`.
* `TauCeti.Multiquadratic.finrank_intermediateField_sqrtPrimes_eq_two_pow` and
  `TauCeti.Multiquadratic.finrank_intermediateField_sqrtPrimes_eq_two_iff`: the degree and
  quadratic-subfield readings for `intermediateFieldEquivSubmoduleSqrtPrimes`.
-/

public section

open IntermediateField Module

namespace TauCeti.Multiquadratic

variable {ι : Type*}

section PrimeFamily

variable [Finite ι] (p : ι → ℕ) (hp : ∀ i, (p i).Prime) (hinj : Function.Injective p)

include hp hinj

/-- The subspace attached by the public prime-radicand dictionary is extensionally the same as
the generic dictionary fed the prime-family square-class independence proof. This lets consumers
use the degree theorems from `SubfieldDegree` with
`intermediateFieldEquivSubmoduleSqrtPrimes` without a parallel prime-specific degree API. -/
theorem intermediateFieldEquivSubmoduleSqrtPrimes_apply_ofDual_eq
    (F : IntermediateField ℚ (adjoin ℚ (Set.range fun i => (Real.sqrt (p i) : ℝ)))) :
    (intermediateFieldEquivSubmoduleSqrtPrimes p hp hinj F).ofDual =
      (intermediateFieldEquivSubmodule (fun i => sq_sqrt_natCast (p i))
        (not_isSquare_prod_primes_of_injective p hp hinj) F).ofDual := by
  ext v
  rw [mem_intermediateFieldEquivSubmoduleSqrtPrimes_apply_ofDual_iff,
    mem_intermediateFieldEquivSubmodule_apply_ofDual_iff]
  rfl

/-- **Degree/subspace-size relation for `ℚ(√p₁, …, √pₙ)`.** For an intermediate field `F`
of a prime-radicand multiquadratic field, `[F : ℚ]` times the size of its attached subspace is
`2 ^ |ι|`. -/
theorem finrank_mul_card_intermediateFieldEquivSubmoduleSqrtPrimes
    (F : IntermediateField ℚ (adjoin ℚ (Set.range fun i => (Real.sqrt (p i) : ℝ)))) :
    Module.finrank ℚ F
        * Nat.card (intermediateFieldEquivSubmoduleSqrtPrimes p hp hinj F).ofDual
      = 2 ^ Nat.card ι := by
  rw [intermediateFieldEquivSubmoduleSqrtPrimes_apply_ofDual_eq p hp hinj F]
  exact finrank_mul_card_intermediateFieldEquivSubmodule (fun i => sq_sqrt_natCast (p i))
    (not_isSquare_prod_primes_of_injective p hp hinj) F

/-- **Degree of a prime-radicand intermediate field.** The degree of an intermediate field of
`ℚ(√p₁, …, √pₙ)` is `2` to the codimension of its attached prime-radicand subspace. -/
theorem finrank_intermediateField_sqrtPrimes_eq_two_pow
    (F : IntermediateField ℚ (adjoin ℚ (Set.range fun i => (Real.sqrt (p i) : ℝ)))) :
    Module.finrank ℚ F =
      2 ^ (Nat.card ι - Module.finrank (ZMod 2)
        (intermediateFieldEquivSubmoduleSqrtPrimes p hp hinj F).ofDual) := by
  rw [intermediateFieldEquivSubmoduleSqrtPrimes_apply_ofDual_eq p hp hinj F]
  exact finrank_intermediateField_eq_two_pow (fun i => sq_sqrt_natCast (p i))
    (not_isSquare_prod_primes_of_injective p hp hinj) F

/-- **Quadratic subfields of `ℚ(√p₁, …, √pₙ)`.** An intermediate field has degree `2` exactly
when its attached prime-radicand subspace is a hyperplane. -/
theorem finrank_intermediateField_sqrtPrimes_eq_two_iff
    (F : IntermediateField ℚ (adjoin ℚ (Set.range fun i => (Real.sqrt (p i) : ℝ)))) :
    Module.finrank ℚ F = 2 ↔
      Module.finrank (ZMod 2)
          (intermediateFieldEquivSubmoduleSqrtPrimes p hp hinj F).ofDual + 1 = Nat.card ι := by
  rw [intermediateFieldEquivSubmoduleSqrtPrimes_apply_ofDual_eq p hp hinj F]
  exact finrank_intermediateField_eq_two_iff (fun i => sq_sqrt_natCast (p i))
    (not_isSquare_prod_primes_of_injective p hp hinj) F

end PrimeFamily

end TauCeti.Multiquadratic
