/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import TauCeti.FieldTheory.IntermediateField.Quadratic
import Mathlib.Analysis.Real.Sqrt

/-!
# Square-class descent in multiquadratic towers

For a sequence of chosen square roots `root : ℕ → L` over a base field `K`, the tower
`sqrtTower root n = K(root₀, …, rootₙ₋₁)` is the intermediate field generated by the first
`n` roots. This file proves **square-class descent**: if an element `y` whose square is
`r : K` lies in `sqrtTower root n`, then `r` is a square times a subset product of the
corresponding radicands. The rational-real specialization requires the radicands to be
positive so that `Real.sqrt` supplies the chosen roots.

This is the engine behind the degree computation
`[K(√d₀, …, √dₙ₋₁) : K] = 2ⁿ` for square-class-independent radicands, and hence behind
the structure theory of multiquadratic fields.

## Main definitions and results

* `TauCeti.Multiquadratic.sqrtTower`: the tower `K(root₀, …, rootₙ₋₁)`.
* `TauCeti.Multiquadratic.sqrtTower_succ`: the one-step recursion.
* `TauCeti.Multiquadratic.sqrtTower_root_mem`: the listed roots lie in the tower.
* `TauCeti.Multiquadratic.squareClass_of_sq_mem`: field-generic square-class descent.
* `TauCeti.Multiquadratic.squareClass_of_sqrt_mem`: rational-real square-class descent.

## Provenance

This material is migrated from
[kim-em/erdos-unit-distance](https://github.com/kim-em/erdos-unit-distance), the
formalization of L. Alpöge's disproof of the uniform-constant Erdős unit-distance
conjecture, where it was developed for one specific CM field. Here it is the field-generic
square-class engine of the multiquadratic-fields roadmap.
-/

open IntermediateField

namespace TauCeti.Multiquadratic

variable {K L : Type*} [Field K] [Field L] [Algebra K L]

/-- Iterated multiquadratic tower `K(root₀, …, rootₙ₋₁) ⊆ L`. -/
noncomputable def sqrtTower (root : ℕ → L) (n : ℕ) : IntermediateField K L :=
  IntermediateField.adjoin K (root '' Set.Iio n)

/-- The zeroth multiquadratic tower is the base field. -/
@[simp]
theorem sqrtTower_zero (root : ℕ → L) : sqrtTower (K := K) root 0 = ⊥ := by
  simp [sqrtTower]

/-- Adjoining the next square root gives the successor stage of `sqrtTower`. -/
theorem sqrtTower_succ (root : ℕ → L) (n : ℕ) :
    sqrtTower (K := K) root (n + 1)
      = (sqrtTower (K := K) root n) ⊔ IntermediateField.adjoin K {root n} := by
  rw [sqrtTower, sqrtTower, ← IntermediateField.adjoin_union]
  congr 1
  have hIio : Set.Iio (n + 1) = Set.Iio n ∪ {n} := by
    ext k
    simp only [Set.mem_Iio, Set.mem_union, Set.mem_singleton_iff]
    omega
  rw [hIio, Set.image_union, Set.image_singleton]

/-- A chosen root indexed before `n` lies in `sqrtTower root n`. -/
theorem sqrtTower_root_mem (root : ℕ → L) {j n : ℕ} (hj : j < n) :
    root j ∈ sqrtTower (K := K) root n :=
  IntermediateField.mem_adjoin_of_mem K ⟨j, hj, rfl⟩

/-- The square of a listed root lies in `sqrtTower root n` as soon as its radicand is in the
base field. -/
theorem sqrtTower_sq_mem (root : ℕ → L) (d : ℕ → K)
    (hroot : ∀ j, root j ^ 2 = algebraMap K L (d j)) {j n : ℕ} :
    root j ^ 2 ∈ sqrtTower (K := K) root n := by
  rw [hroot j]
  exact (sqrtTower (K := K) root n).algebraMap_mem (d j)

/-- If one listed root already lies in a stage, adjoining it does not change that stage. -/
theorem sqrtTower_sup_adjoin_eq_of_mem (root : ℕ → L) {n : ℕ}
    (hroot : root n ∈ sqrtTower (K := K) root n) :
    sqrtTower (K := K) root n ⊔ IntermediateField.adjoin K {root n}
      = sqrtTower (K := K) root n := by
  rw [sup_eq_left]
  exact IntermediateField.adjoin_le_iff.mpr (by simpa using hroot)

private theorem algebraMap_eq_iff {a b : K} (h : algebraMap K L a = algebraMap K L b) :
    a = b :=
  RingHom.injective (algebraMap K L) h

/-- **Square-class descent.** If `y² = r` over `K` and `y ∈ K(root₀, …, rootₙ₋₁)`, where
`root j` is a chosen square root of `d j`, then `r` is a square times a subset product of
the `d j` with `j < n`. -/
theorem squareClass_of_sq_mem (d : ℕ → K) (root : ℕ → L)
    (hroot : ∀ j, root j ^ 2 = algebraMap K L (d j)) [NeZero (2 : L)] :
    ∀ n, ∀ r : K, ∀ y : L, y ^ 2 = algebraMap K L r → y ∈ sqrtTower (K := K) root n →
      ∃ (T : Finset ℕ) (s : K), ↑T ⊆ Set.Iio n ∧
        r = s ^ 2 * ∏ j ∈ T, d j := by
  classical
  intro n
  induction n with
  | zero =>
      intro r y hy hmem
      rw [sqrtTower_zero, IntermediateField.mem_bot] at hmem
      obtain ⟨s, rfl⟩ := hmem
      have h2 : s ^ 2 = r := by
        apply algebraMap_eq_iff (K := K) (L := L)
        simpa using hy
      exact ⟨∅, s, by simp, by rw [Finset.prod_empty, mul_one, h2]⟩
  | succ n ih =>
      intro r y hy hmem
      rw [sqrtTower_succ] at hmem
      by_cases hnext : root n ∈ sqrtTower (K := K) root n
      · rw [sqrtTower_sup_adjoin_eq_of_mem root hnext] at hmem
        obtain ⟨T, s, hT, heq⟩ := ih r y hy hmem
        exact ⟨T, s, hT.trans (Set.Iio_subset_Iio n.le_succ), heq⟩
      · have hx2 : root n ^ 2 ∈ sqrtTower (K := K) root n := by
          rw [hroot n]
          exact (sqrtTower (K := K) root n).algebraMap_mem (d n)
        obtain ⟨a, b, ha, hb, heq⟩ :=
          TauCeti.IntermediateField.exists_add_mul_of_mem_sup_adjoin_sq hx2 hmem
        have hsq :
            algebraMap K L r =
              a ^ 2 + b ^ 2 * algebraMap K L (d n) + 2 * a * b * root n := by
          calc
            algebraMap K L r = y ^ 2 := hy.symm
            _ = (a + b * root n) ^ 2 := by rw [heq]
            _ = a ^ 2 + b ^ 2 * algebraMap K L (d n) + 2 * a * b * root n := by
              rw [← hroot n]
              ring
        have hcross_eq :
            2 * a * b * root n =
              algebraMap K L r - a ^ 2 - b ^ 2 * algebraMap K L (d n) := by
          rw [hsq]
          ring
        have hcross_mem : 2 * a * b * root n ∈ sqrtTower (K := K) root n := by
          rw [hcross_eq]
          exact sub_mem
            (sub_mem ((sqrtTower (K := K) root n).algebraMap_mem r) (pow_mem ha 2))
            (mul_mem (pow_mem hb 2) ((sqrtTower (K := K) root n).algebraMap_mem (d n)))
        by_cases hab : a * b = 0
        · rcases mul_eq_zero.mp hab with ha0 | hb0
          · have hy_mul_mem : y * root n ∈ sqrtTower (K := K) root n := by
              have hy_mul_eq : y * root n = b * algebraMap K L (d n) := by
                calc
                  y * root n = (b * root n) * root n := by rw [heq, ha0, zero_add]
                  _ = b * (root n ^ 2) := by ring
                  _ = b * algebraMap K L (d n) := by rw [hroot n]
              rw [hy_mul_eq]
              exact mul_mem hb ((sqrtTower (K := K) root n).algebraMap_mem (d n))
            have hy_mul_sq : (y * root n) ^ 2 = algebraMap K L (r * d n) := by
              rw [map_mul, ← hy, ← hroot n]
              ring
            obtain ⟨T, s, hT, hmul⟩ := ih (r * d n) (y * root n) hy_mul_sq hy_mul_mem
            have hnT : n ∉ T := by
              intro hn
              exact (Nat.lt_irrefl n) (hT hn)
            refine ⟨insert n T, s / d n, ?_, ?_⟩
            · intro j hj
              rw [Finset.mem_coe, Finset.mem_insert] at hj
              rw [Set.mem_Iio]
              rcases hj with rfl | hj
              · omega
              · exact Nat.lt_trans (hT hj) n.lt_succ_self
            · have hdn0 : d n ≠ 0 := by
                intro hdn
                apply hnext
                have hroot_zero : root n = 0 := by
                  apply eq_zero_of_pow_eq_zero
                  rw [hroot n, hdn, map_zero]
                rw [hroot_zero]
                exact zero_mem _
              rw [Finset.prod_insert hnT]
              calc
                r = (r * d n) / d n := by field_simp [hdn0]
                _ = (s ^ 2 * ∏ j ∈ T, d j) / d n := by rw [hmul]
                _ = (s / d n) ^ 2 * (d n * ∏ j ∈ T, d j) := by
                  field_simp [hdn0]
          · have hy_mem : y ∈ sqrtTower (K := K) root n := by
              rw [heq, hb0, zero_mul, add_zero]
              exact ha
            obtain ⟨T, s, hT, hres⟩ := ih r y hy hy_mem
            exact ⟨T, s, hT.trans (Set.Iio_subset_Iio n.le_succ), hres⟩
        · have hcoef_mem : 2 * a * b ∈ sqrtTower (K := K) root n :=
            mul_mem (mul_mem ((sqrtTower (K := K) root n).natCast_mem 2) ha) hb
          have hcoef_ne : 2 * a * b ≠ 0 := by
            have h2ab : (2 : L) * (a * b) ≠ 0 := mul_ne_zero (NeZero.ne (2 : L)) hab
            simpa [mul_assoc] using h2ab
          have hroot_mem : root n ∈ sqrtTower (K := K) root n := by
            have hmem' := mul_mem (inv_mem hcoef_mem) hcross_mem
            have hEq : (2 * a * b)⁻¹ * (2 * a * b * root n) = root n := by
              rw [← mul_assoc, inv_mul_cancel₀ hcoef_ne, one_mul]
            rw [← hEq]
            exact hmem'
          exact (hnext hroot_mem).elim

/-- **Square-class descent for real rational square roots.** If `0 < r` is rational with
`√r ∈ ℚ(√c₀, …, √cₙ₋₁)` and every `c j` is positive, then `r` is a rational square times a
subset product of the `c j`. -/
theorem squareClass_of_sqrt_mem (c : ℕ → ℚ) (hc : ∀ j, 0 < c j) :
    ∀ n, ∀ r : ℚ, 0 < r → (Real.sqrt r : ℝ) ∈ sqrtTower (K := ℚ) (fun j => Real.sqrt (c j)) n →
      ∃ (T : Finset ℕ) (s : ℚ), ↑T ⊆ Set.Iio n ∧
        r = s ^ 2 * ∏ j ∈ T, c j := by
  intro n r hr hmem
  apply squareClass_of_sq_mem c (fun j => Real.sqrt (c j)) ?_ n r (Real.sqrt r) ?_ hmem
  · intro j
    have hcj_nonneg : 0 ≤ (c j : ℝ) := by exact_mod_cast (hc j).le
    simpa using Real.sq_sqrt hcj_nonneg
  · have hr_nonneg : 0 ≤ (r : ℝ) := by exact_mod_cast hr.le
    simpa using Real.sq_sqrt hr_nonneg

end TauCeti.Multiquadratic
