name = "web"
defaultTargets = ["web"]

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso.git"
rev = "v4.31.0-rc1"

[[lean_lib]]
name = "Site"

[[lean_exe]]
name = "web"
root = "Main"
supportInterpreter = true
